const _fl_str = (...xs) => xs.map(x => x==null?'null':String(x)).join('');const _fl_length = (x) => (x==null ? 0 : x.length);const _fl_substring = (s, a, b) => (b==null ? s.slice(a) : s.slice(a, b));const _fl_char_at = (s, i) => (s[i] || null);const _fl_replace = (s, a, b) => s.split(a).join(b);const _fl_starts_with = (s, p) => s.startsWith(p);const _fl_ends_with = (s, p) => s.endsWith(p);const _fl_contains = (s, p) => s.includes(p);const _fl_split = (s, sep) => s.split(sep);const _fl_join = (l, sep) => l.join(sep==null?'':sep);const _fl_trim = (s) => s.trim();const _fl_upper = (s) => s.toUpperCase();const _fl_lower = (s) => s.toLowerCase();const _fl_repeat = (s, n) => s.repeat(n);const _fl_index_of = (s, p) => s.indexOf(p);const _fl_first = (l) => (l==null || l.length===0 ? null : l[0]);const _fl_last = (l) => (l==null || l.length===0 ? null : l[l.length-1]);const _fl_rest = (l) => (l==null || l.length===0 ? [] : l.slice(1));const _fl_append = (a, b) => (Array.isArray(b) ? [...a, ...b] : [...a, b]);const _fl_slice = (l, a, b) => l.slice(a, b);const _fl_map = (f, l) => l.map(x => f(x));const _fl_filter = (f, l) => l.filter(x => f(x));const _fl_reduce = (f, init, l) => l.reduce((acc, x) => f(acc, x), init);const _fl_find = (f, l) => (l.find(x => f(x)) ?? null);const _fl_every = (f, l) => l.every(x => f(x));const _fl_some = (f, l) => l.some(x => f(x));const _fl_sort = (l, cmp) => [...l].sort(cmp || ((a,b)=>a<b?-1:a>b?1:0));const _fl_reverse = (l) => [...l].reverse();const _fl_flatten = (l) => l.flat(Infinity);const _fl_distinct = (l) => [...new Set(l)];const _fl_range = (a, b, s) => { let r=[]; let step=s||1; for(let i=a;i<b;i+=step)r.push(i); return r; };const _fl_take = (n, l) => l.slice(0, n);const _fl_drop = (n, l) => l.slice(n);const _fl_get = (o, k) => (o==null ? null : (o[k]===undefined ? null : o[k]));const _fl_keys = (o) => (o==null ? [] : Object.keys(o));const _fl_values = (o) => (o==null ? [] : Object.values(o));const _fl_entries = (o) => (o==null ? [] : Object.entries(o).map(([k,v])=>[k,v]));const _fl_has_key = (o, k) => (o!=null && k in o);const _fl_map_set = (o, k, v) => ({...o, [k]: v});const _fl_map_delete = (o, k) => { const c={...o}; delete c[k]; return c; };const _fl_merge = (...os) => Object.assign({}, ...os);const _fl_is_map = (x) => (x!=null && typeof x==='object' && !Array.isArray(x));const _fl_type_of = (x) => (x==null?'null':Array.isArray(x)?'list':typeof x);const map_entries = (m) => m instanceof Map ? [...m.entries()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.entries(m) : []);const map_keys = (m) => m instanceof Map ? [...m.keys()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.keys(m) : []);const map_values = (m) => m instanceof Map ? [...m.values()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.values(m) : []);const now = () => Date.now();const now_ms = () => Date.now();const now_iso = () => new Date().toISOString();const now_unix = () => Math.floor(Date.now()/1000);const regex_match = (s, p) => new RegExp(p).test(s);const regex_find = (s, p) => { const m = s.match(new RegExp(p)); return m ? m[0] : null; };const regex_find_all = (s, p) => s.match(new RegExp(p, 'g')) || [];const regex_replace = (s, p, r) => s.replace(new RegExp(p, 'g'), r);const regex_split = (s, p) => s.split(new RegExp(p));const regex_count = (s, p) => (s.match(new RegExp(p, 'g')) || []).length;const regex_extract = (s, p) => { const m = s.match(new RegExp(p)); return m ? m.slice(1) : []; };const _fl_file_read = (p) => require('fs').readFileSync(p, 'utf8');const _fl_file_write = (p, c) => require('fs').writeFileSync(p, c);const _fl_file_exists = (p) => require('fs').existsSync(p);const _fl_shell_capture = (cmd) => { try { const {execSync}=require('child_process'); return {stdout:execSync(cmd,{encoding:'utf8'}),stderr:'',code:0}; } catch(e) { return {stdout:'',stderr:String(e),code:1}; } };const _fl_empty_q = (x) => (x==null || x.length===0);const __argv__ = process.argv.slice(2);const _fl_pg_exec = (db,sql,...args) => null;const _fl_pg_query = (db,sql,...args) => [];const _fl_pg_connect = (cfg) => null;const _fl_mariadb_exec = (db,sql,...args) => null;const _fl_mariadb_query = (db,sql,...args) => [];const _fl_mariadb_one = (db,sql,...args) => null;const _fl_db_query = (path,sql,...args) => [];const _fl_db_exec = (path,sql,...args) => null;const _fl_server_post = (path,fn) => null;const _fl_server_get = (path,fn) => null;const _fl_server_put = (path,fn) => null;const _fl_server_delete = (path,fn) => null;const _fl_server_start = (port) => null;const _fl_server_stop = () => null;const _fl_http_get = (url) => '';const _fl_http_post = (url,body) => '';const _fl_ws_send = (sid,data) => null;
const is_digit_q = (c)=>((c==null)?false:((c>="0")&&(c<="9")));;
const is_alpha_q = (c)=>((c==null)?false:(((c>="a")&&(c<="z"))||((c>="A")&&(c<="Z"))));;
const is_alnum_q = (c)=>(is_digit_q(c)||is_alpha_q(c));;
const is_space_q = (c)=>((c===" ")||(c==="\t")||(c==="\n")||(c==="\r"));;
const is_symbol_char_q = (c)=>((c==null)?false:(is_alnum_q(c)||(c==="-")||(c==="_")||(c==="?")||(c==="!")||(c==="/")||(c===".")||(c==="<")||(c===">")||(c==="=")||(c==="+")||(c==="*")||(c==="%")||(c==="&")||(c==="|")||(c==="^")||(c==="~")));;
const make_state = (src)=>({});;
const peek_at = (st,offset)=>((()=>{let src=_fl_get(st,"src");let i=(_fl_get(st,"idx")+offset);return ((i>=_fl_length(src))?null:_fl_char_at(src,i));})());;
const peek = (st)=>peek_at(st,0);;
const at_end_q = (st)=>(_fl_get(st,"idx")>=_fl_length(_fl_get(st,"src")));;
const advance = (st)=>((()=>{let c=peek(st);return ((c==="\n")?({}):({}));})());;
const emit = (st,kind,value,sl,sc)=>({});;
const skip_comment = (st)=>(at_end_q(st)?st:((()=>{let c=peek(st);return ((c==="\n")?advance(st):skip_comment(advance(st)));})()));;
const skip_ws = (st)=>(at_end_q(st)?st:((()=>{let c=peek(st);return ;})()));;
const read_number_body = (st,acc,has_dot,line,col)=>(at_end_q(st)?emit(st,"Number",acc,line,col):((()=>{let c=peek(st);return ;})()));;
const read_number = (st)=>read_number_body(st,"",false,_fl_get(st,"line"),_fl_get(st,"col"));;
const translate_esc = (c)=>((c==="n")?"\n":((c==="t")?"\t":((c==="r")?"\r":((c==="\"")?"\"":((c==="\\")?"\\":(true?c:null))))));;
const read_string_body = (st,acc,line,col)=>(at_end_q(st)?emit(st,"String",acc,line,col):((()=>{let c=peek(st);return ;})()));;
const read_string = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_string_body(st1,"",line,col);})());;
const read_symbol_body_kind = (st,acc,line,col,kind)=>(at_end_q(st)?emit(st,kind,acc,line,col):((()=>{let c=peek(st);return (is_symbol_char_q(c)?read_symbol_body_kind(advance(st),_fl_str(acc,c),line,col,kind):emit(st,kind,acc,line,col));})()));;
const read_symbol = (st)=>read_symbol_body_kind(st,"",_fl_get(st,"line"),_fl_get(st,"col"),"Symbol");;
const read_variable = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Variable");})());;
const read_keyword = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Keyword");})());;
const read_token = (st)=>((()=>{let st1=skip_ws(st);return (at_end_q(st1)?st1:((()=>{let c=peek(st1);let line=_fl_get(st1,"line");let col=_fl_get(st1,"col");return ;})()));})());;
const lex_loop = (st)=>((()=>{let st1=skip_ws(st);return (at_end_q(st1)?_fl_get(st1,"tokens"):lex_loop(read_token(st1)));})());;
const lex = (src)=>lex_loop(make_state(src));;
const make_literal = (type,value,line)=>({});;
const make_variable = (name,line)=>({});;
const make_keyword = (name,line)=>({});;
const make_sexpr = (op,args,line)=>({});;
const make_array_block = (items,line)=>({});;
const make_map_block = (items,line)=>({});;
const make_block = (type,name,fields,line)=>({});;
const p_make = (tokens)=>({});;
const p_peek = (p)=>((()=>{let i=_fl_get(p,"idx");let t=_fl_get(p,"tokens");return ((i>=_fl_length(t))?null:_fl_get(t,i));})());;
const p_peek_at = (p,offset)=>((()=>{let i=(_fl_get(p,"idx")+offset);let t=_fl_get(p,"tokens");return ((i>=_fl_length(t))?null:_fl_get(t,i));})());;
const p_end_q = (p)=>(_fl_get(p,"idx")>=_fl_length(_fl_get(p,"tokens")));;
const p_advance = (p)=>({});;
const p_with_ast = (p,ast)=>({});;
const p_append_ast = (p,node)=>p_with_ast(p,_fl_append(_fl_get(p,"ast"),[node]));;
const r_pair = (p,node)=>({});;
const parse_atom = (p)=>((()=>{let t=p_peek(p);let k=_fl_get(t,"kind");let v=_fl_get(t,"value");let line=_fl_get(t,"line");return ;})());;
const parse_expr = (p)=>((()=>{let t=p_peek(p);let k=_fl_get(t,"kind");return ;})());;
const parse_sexpr = (p)=>((()=>{let start_tok=p_peek(p);let line=_fl_get(start_tok,"line");let p1=p_advance(p);let first=parse_args(p1,[]);let p2=_fl_get(first,"p");let args=_fl_get(first,"node");return ((_fl_length(args)===0)?r_pair(parse_consume_rparen(p2),make_sexpr("",[],line)):((()=>{let op_node=_fl_get(args,0);let op=((_fl_get(op_node,"kind")==="literal")?_fl_get(op_node,"value"):((_fl_get(op_node,"kind")==="variable")?_fl_str("$",_fl_get(op_node,"name")):"unknown"));let rest=_fl_slice(args,1,_fl_length(args));return r_pair(parse_consume_rparen(p2),make_sexpr(op,rest,line));})()));})());;
const parse_consume_rparen = (p)=>((()=>{let t=p_peek(p);return (((!(t==null))&&(_fl_get(t,"kind")==="RParen"))?p_advance(p):p);})());;
const parse_args = (p,acc)=>((()=>{let t=p_peek(p);return ;})());;
const parse_bracket = (p)=>((()=>{let tok=p_peek(p);let line=_fl_get(tok,"line");let p1=p_advance(p);let next=p_peek(p1);return (((!(next==null))&&(_fl_get(next,"kind")==="Symbol")&&is_block_type_q(_fl_get(next,"value"))&&(_fl_get(next,"value")===upper_case(_fl_get(next,"value"))))?parse_named_block(p1,line):parse_array(p1,line));})());;
const is_block_type_q = (s)=>((()=>{let c=_fl_char_at(s,0);return ((c>="A")&&(c<="Z"));})());;
const upper_case = (s)=>s;;
const parse_array = (p,line)=>((()=>{let collected=parse_args(p,[]);let p2=_fl_get(collected,"p");let items=_fl_get(collected,"node");return r_pair(parse_consume_rbracket(p2),make_array_block(items,line));})());;
const parse_consume_rbracket = (p)=>((()=>{let t=p_peek(p);return (((!(t==null))&&(_fl_get(t,"kind")==="RBracket"))?p_advance(p):p);})());;
const parse_named_block = (p,line)=>((()=>{let type_tok=p_peek(p);let type=_fl_get(type_tok,"value");let p1=p_advance(p);let name_info=parse_optional_name(p1);let p2=_fl_get(name_info,"p");let name=_fl_get(name_info,"node");let fields_info=parse_block_fields(p2,({}));let p3=_fl_get(fields_info,"p");let fields=_fl_get(fields_info,"node");return r_pair(parse_consume_rbracket(p3),make_block(type,name,fields,line));})());;
const parse_optional_name = (p)=>((()=>{let t=p_peek(p);return (((!(t==null))&&(_fl_get(t,"kind")==="Symbol")&&(!(_fl_char_at(_fl_get(t,"value"),0)===":")))?r_pair(p_advance(p),_fl_get(t,"value")):r_pair(p,null));})());;
const parse_block_fields = (p,acc)=>((()=>{let t=p_peek(p);return ;})());;
const parse_map = (p)=>((()=>{let tok=p_peek(p);let line=_fl_get(tok,"line");let p1=p_advance(p);let collected=parse_args(p1,[]);let p2=_fl_get(collected,"p");let items=_fl_get(collected,"node");return r_pair(parse_consume_rbrace(p2),make_map_block(items,line));})());;
const parse_consume_rbrace = (p)=>((()=>{let t=p_peek(p);return (((!(t==null))&&(_fl_get(t,"kind")==="RBrace"))?p_advance(p):p);})());;
const parse_all = (p)=>(p_end_q(p)?_fl_get(p,"ast"):((()=>{let one=parse_expr(p);let p2=p_append_ast(_fl_get(one,"p"),_fl_get(one,"node"));return parse_all(p2);})()));;
const parse = (tokens)=>parse_all(p_make(tokens));;
const make_literal = (type,value,line)=>({});;
const make_variable = (name,line)=>({});;
const make_keyword = (name,line)=>({});;
const make_sexpr = (op,args,line)=>({});;
const make_number = (v,line)=>make_literal("number",v,line);;
const make_string = (v,line)=>make_literal("string",v,line);;
const make_bool = (v,line)=>make_literal("boolean",v,line);;
const make_null = (line)=>make_literal("null",null,line);;
const make_symbol = (v,line)=>make_literal("symbol",v,line);;
const make_block = (type,name,fields,line)=>({});;
const make_array_block = (items,line)=>make_block("Array",null,({}),line);;
const make_map_block = (items,line)=>make_block("Map",null,({}),line);;
const make_pattern_literal = (value,line)=>({});;
const make_pattern_variable = (name,line)=>({});;
const make_pattern_wildcard = (line)=>({});;
const make_pattern_list = (items,rest,line)=>({});;
const make_pattern_struct = (type_name,fields,line)=>({});;
const make_pattern_or = (alternatives,line)=>({});;
const make_pattern_range = (start,end,line)=>({});;
const make_pattern_match = (value,cases,line)=>({});;
const make_match_case = (pattern,guard,body,line)=>({});;
const make_function_value = (params,body,captured_env,name)=>({});;
const make_type_class = (name,generics,methods,line)=>({});;
const make_type_class_instance = (class_name,type_name,impls,line)=>({});;
const make_module_block = (name,exports,body,line)=>({});;
const make_import_block = (path,alias,names,line)=>({});;
const make_open_block = (module_name,line)=>({});;
const make_search_block = (query,fields,line)=>({});;
const make_learn_block = (topic,fields,line)=>({});;
const make_reasoning_block = (name,fields,line)=>({});;
const make_async_function = (name,params,body,line)=>({});;
const make_await = (expr,line)=>({});;
const make_try = (body,catch_,finally_,line)=>({});;
const make_catch = (param,body,line)=>({});;
const make_throw = (expr,line)=>({});;
const make_page = (name,path,fields,line)=>({});;
const make_route = (method,path,handler,line)=>({});;
const make_component = (name,fields,line)=>({});;
const make_form = (name,fields,line)=>({});;
const deep_equal_q = (a,b)=>(((a==null)&&(b==null))?true:(((a==null)||(b==null))?false:((Array.isArray(a)&&Array.isArray(b))?deep_equal_list_q(a,b,0):((_fl_is_map(a)&&_fl_is_map(b))?deep_equal_map_q(a,b):(true?(a===b):null)))));;
const deep_equal_list_q = (a,b,i)=>((!(_fl_length(a)===_fl_length(b)))?false:((i>=_fl_length(a))?true:((!deep_equal_q(_fl_get(a,i),_fl_get(b,i)))?false:(true?deep_equal_list_q(a,b,(i+1)):null))));;
const deep_equal_map_q = (a,b)=>((()=>{let ka=keys_no_line(a);let kb=keys_no_line(b);return ((!(_fl_length(ka)===_fl_length(kb)))?false:deep_equal_map_keys_q(a,b,ka,0));})());;
const keys_no_line = (m)=>_fl_filter(((k)=>(!(k==="line"))),json_keys(m));;
const deep_equal_map_keys_q = (a,b,ks,i)=>((i>=_fl_length(ks))?true:(((()=>{let k=_fl_get(ks,i);return (!deep_equal_q(_fl_get(a,k),_fl_get(b,k)));})())?false:(true?deep_equal_map_keys_q(a,b,ks,(i+1)):null)));;
const list_q = (v)=>((v==null)?false:(Number(_fl_str("[",v))===null));;
const map_q = (v)=>((v==null)?false:(!(_fl_get(v,"kind")==null)));;
const esc_1 = (s)=>_fl_replace(s,"\\","\\\\");;
const esc_2 = (s)=>_fl_replace(s,"\"","\\\"");;
const esc_3 = (s)=>_fl_replace(s,"\n","\\n");;
const esc_4 = (s)=>_fl_replace(s,"\r","\\r");;
const esc_5 = (s)=>_fl_replace(s,"\t","\\t");;
const js_esc_inner = (s)=>esc_5(esc_4(esc_3(esc_2(esc_1(s)))));;
const js_esc = (s)=>_fl_str("\"",js_esc_inner(s),"\"");;
const js_reserved_q = (n)=>((n==="default")||(n==="class")||(n==="const")||(n==="let")||(n==="if")||(n==="else")||(n==="switch")||(n==="case")||(n==="break")||(n==="continue")||(n==="for")||(n==="while")||(n==="function")||(n==="return")||(n==="throw")||(n==="try")||(n==="catch")||(n==="new")||(n==="delete")||(n==="typeof")||(n==="instanceof")||(n==="var")||(n==="in")||(n==="of")||(n==="this")||(n==="super")||(n==="void")||(n==="yield")||(n==="async")||(n==="await")||(n==="import")||(n==="export")||(n==="enum")||(n==="do")||(n==="with")||(n==="finally")||(n==="null")||(n==="true")||(n==="false"));;
const rename_1 = (n)=>_fl_replace(n,"-","_");;
const rename_2 = (n)=>_fl_replace(n,"?","_q");;
const rename_3 = (n)=>_fl_replace(n,"!","_x");;
const rename_4 = (n)=>_fl_replace(n,">","_gt");;
const rename_5 = (n)=>_fl_replace(n,"<","_lt");;
const rename_6 = (n)=>_fl_replace(n,"*","_st");;
const rename_7 = (n)=>_fl_replace(n,"+","_pl");;
const js_name_inner = (n)=>((()=>{let g=rename_7(rename_6(rename_5(rename_4(rename_3(rename_2(rename_1(n)))))));return (js_reserved_q(g)?_fl_str(g,"_"):g);})());;
const js_name = (n)=>((n==null)?"_":js_name_inner(n));;
const cg = (n)=>((n==null)?"null":((_fl_get(n,"kind")==="literal")?cg_literal(n):((_fl_get(n,"kind")==="variable")?js_name(_fl_get(n,"name")):((_fl_get(n,"kind")==="keyword")?js_esc(_fl_get(n,"name")):((_fl_get(n,"kind")==="sexpr")?cg_sexpr(n):((_fl_get(n,"kind")==="block")?cg_block(n):((_fl_get(n,"kind")==="pattern-match")?cg_match(n):((_fl_get(n,"kind")==="await")?_fl_str("(await ",cg(_fl_get(n,"argument")),")"):((_fl_get(n,"kind")==="throw")?_fl_str("(()=>{throw new Error(String(",cg(_fl_get(n,"argument")),"))})()"):(true?"null":null))))))))));;
const cg_literal = (n)=>((()=>{let t=_fl_get(n,"type");let v=_fl_get(n,"value");return ;})());;
const cg_block = (n)=>((()=>{let t=_fl_get(n,"type");return ;})());;
const cg_map_entries = (fields)=>((()=>{let items_val=_fl_get(fields,"items");return (Array.isArray(items_val)?cg_map_flat_loop(items_val,0,""):cg_map_loop([],0,""));})());;
const cg_map_loop_inner = (entries,i,acc,e)=>((()=>{let k=_fl_get(e,0);let v=cg(_fl_get(e,1));let pair=_fl_str(js_esc(k),":",v);return cg_map_loop(entries,(i+1),((i===0)?pair:_fl_str(acc,",",pair)));})());;
const cg_map_loop = (entries,i,acc)=>((i>=_fl_length(entries))?acc:cg_map_loop_inner(entries,i,acc,_fl_get(entries,i)));;
const cg_map_flat_loop_inner = (items,i,acc,k_n,v_n)=>((()=>{let k_str=cg_keyword_key(k_n);let v_js=_fl_str(cg(v_n));let pair=_fl_str(k_str,":",v_js);return cg_map_flat_loop(items,(i+2),((i===0)?pair:_fl_str(acc,",",pair)));})());;
const cg_map_flat_loop = (items,i,acc)=>((i>=_fl_length(items))?acc:cg_map_flat_loop_inner(items,i,acc,_fl_get(items,i),_fl_get(items,(i+1))));;
const cg_keyword_key = (n)=>((_fl_get(n,"kind")==="keyword")?js_esc(_fl_get(n,"name")):((_fl_get(n,"kind")==="literal")?js_esc(_fl_str(_fl_get(n,"value"))):(true?"\"_anon\"":null)));;
const cg_func_block_inner = (name,fields,pnode,body)=>((()=>{let pitems=((pnode==null)?[]:_fl_get(_fl_get(pnode,"fields"),"items"));let ps=extract_params(pitems);return _fl_str("const ",name," = (",ps,")=>",cg(body),";");})());;
const cg_func_block = (n)=>((()=>{let name=js_name(_fl_get(n,"name"));let fields=_fl_get(n,"fields");return cg_func_block_inner(name,fields,_fl_get(fields,"params"),_fl_get(fields,"body"));})());;
const cg_if = (args)=>_fl_str("(",cg(_fl_get(args,0)),"?",cg(_fl_get(args,1)),":",((_fl_length(args)>=3)?cg(_fl_get(args,2)):"null"),")");;
const cg_fn = (args)=>((()=>{let pnode=_fl_get(args,0);let body=_fl_get(args,1);let ps=extract_params(_fl_get(_fl_get(pnode,"fields"),"items"));return _fl_str("((",ps,")=>",cg(body),")");})());;
const cg_defn = (args)=>((()=>{let name_n=_fl_get(args,0);let pnode=_fl_get(args,1);let body=_fl_get(args,2);let name=extract_name(name_n);let ps=extract_params(_fl_get(_fl_get(pnode,"fields"),"items"));return _fl_str("const ",name," = (",ps,")=>",cg(body));})());;
const cg_define = (args)=>((_fl_length(args)===2)?_fl_str("const ",extract_name(_fl_get(args,0))," = ",cg(_fl_get(args,1))):cg_defn(args));;
const cg_let = (args)=>((()=>{let bnode=_fl_get(args,0);let items=_fl_get(_fl_get(bnode,"fields"),"items");let first_item=((items==null)?null:_fl_get(items,0));let nested=((first_item==null)?false:((_fl_get(first_item,"kind")==="block")&&(_fl_get(first_item,"type")==="Array")));let bindings=(nested?cg_let_2d(items,0,""):cg_let_1d(items,0,""));let body_args=_fl_slice(args,1,_fl_length(args));let body_js=cg_do_body(body_args,0,"");return _fl_str("((()=>{",bindings,body_js,"})())");})());;
const cg_let_1d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let k_n=_fl_get(items,i);let v_n=_fl_get(items,(i+1));let name=extract_name(k_n);let val=cg(v_n);return cg_let_1d(items,(i+2),_fl_str(acc,"let ",name,"=",val,";"));})()));;
const cg_let_2d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let pair=_fl_get(items,i);let pitems=_fl_get(_fl_get(pair,"fields"),"items");let k_n=_fl_get(pitems,0);let v_n=_fl_get(pitems,1);let name=extract_name(k_n);let val=cg(v_n);return cg_let_2d(items,(i+1),_fl_str(acc,"let ",name,"=",val,";"));})()));;
const cg_do = (args)=>((_fl_length(args)===0)?"null":_fl_str("(()=>{",cg_do_body(args,0,""),"})()"));;
const cg_do_body = (args,i,acc)=>((i>=_fl_length(args))?acc:((()=>{let last=(i===(_fl_length(args)-1));let c=cg(_fl_get(args,i));let sep=(last?"return ":"");return cg_do_body(args,(i+1),_fl_str(acc,sep,c,";"));})()));;
const cg_cond = (args)=>cg_cond_loop(args,0);;
const cg_cond_loop = (args,i)=>((()=>{let j=(_fl_length(args)-1);let acc="null";while(true){let __r=(()=>{return ((j<0)?acc:((()=>{let clause=_fl_get(args,j);let citems=_fl_get(_fl_get(clause,"fields"),"items");let test=cg(_fl_get(citems,0));let result=cg(_fl_get(citems,1));return {__recur:true,a:[(j-1),_fl_str("(",test,"?",result,":",acc,")")]};})()));})();if(__r&&__r.__recur){[j,acc]=__r.a;continue;}return __r;}})());;
const cg_and = (args)=>((_fl_length(args)===0)?"true":_fl_str("(",and_loop(args,0,""),")"));;
const and_loop = (args,i,acc)=>((i>=_fl_length(args))?acc:((()=>{let c=_fl_str(cg(_fl_get(args,i)));return and_loop(args,(i+1),((i===0)?c:_fl_str(acc,"&&",c)));})()));;
const cg_or = (args)=>((_fl_length(args)===0)?"false":_fl_str("(",or_loop(args,0,""),")"));;
const or_loop = (args,i,acc)=>((i>=_fl_length(args))?acc:((()=>{let c=_fl_str(cg(_fl_get(args,i)));return or_loop(args,(i+1),((i===0)?c:_fl_str(acc,"||",c)));})()));;
const cg_quote = (args)=>((_fl_length(args)===0)?"null":js_esc(_fl_str(cg(_fl_get(args,0)))));;
const cg_set_x = (args)=>_fl_str("(",extract_name(_fl_get(args,0)),"=",cg(_fl_get(args,1)),")");;
const cg_throw = (args)=>((()=>{let m=((_fl_length(args)===0)?"\"error\"":cg(_fl_get(args,0)));return _fl_str("(()=>{throw new Error(String(",m,"))})()");})());;
const cg_try = (args)=>((()=>{let body=cg(_fl_get(args,0));let catch_node=((_fl_length(args)>=2)?_fl_get(args,1):null);let catch_info=((catch_node==null)?null:extract_catch(catch_node));let evar=((catch_info==null)?"_err":_fl_get(catch_info,"evar"));let ebody=((catch_info==null)?"null":_fl_get(catch_info,"ebody"));return _fl_str("(()=>{try{return ",body,";}catch(",evar,"){return ",ebody,";}})()");})());;
const extract_catch = (n)=>((()=>{let args=_fl_get(n,"args");let ev=extract_name(_fl_get(args,0));let handler=cg(_fl_get(args,1));return ({});})());;
const cg_while = (args)=>((()=>{let cond=cg(_fl_get(args,0));let body_args=_fl_slice(args,1,_fl_length(args));let body=while_body(body_args,0,"");return _fl_str("(()=>{while(",cond,"){",body,"}})()");})());;
const while_body = (args,i,acc)=>((i>=_fl_length(args))?acc:while_body(args,(i+1),_fl_str(acc,cg(_fl_get(args,i)),";")));;
const cg_loop = (args)=>((()=>{let bnode=_fl_get(args,0);let items=_fl_get(_fl_get(bnode,"fields"),"items");let first=((items==null)?null:_fl_get(items,0));let nested=((first==null)?false:((_fl_get(first,"kind")==="block")&&(_fl_get(first,"type")==="Array")));let bindings=(nested?loop_inits_2d(items,0,""):loop_inits_1d(items,0,""));let names=(nested?loop_names_2d(items,0,""):loop_names_1d(items,0,""));let body_args=_fl_slice(args,1,_fl_length(args));let body_js=cg_do_body(body_args,0,"");return _fl_str("((()=>{",bindings,"while(true){let __r=(()=>{",body_js,"})();","if(__r&&__r.__recur){[",names,"]=__r.a;continue;}","return __r;}})())");})());;
const loop_inits_1d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let k=_fl_get(items,i);let v=_fl_get(items,(i+1));return loop_inits_1d(items,(i+2),_fl_str(acc,"let ",extract_name(k),"=",cg(v),";"));})()));;
const loop_inits_2d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let pair=_fl_get(items,i);let pit=_fl_get(_fl_get(pair,"fields"),"items");return loop_inits_2d(items,(i+1),_fl_str(acc,"let ",extract_name(_fl_get(pit,0)),"=",cg(_fl_get(pit,1)),";"));})()));;
const loop_names_1d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let k=_fl_get(items,i);let n=extract_name(k);return loop_names_1d(items,(i+2),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));;
const loop_names_2d = (items,i,acc)=>((i>=_fl_length(items))?acc:((()=>{let pair=_fl_get(items,i);let pit=_fl_get(_fl_get(pair,"fields"),"items");let n=extract_name(_fl_get(pit,0));return loop_names_2d(items,(i+1),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));;
const cg_recur = (args)=>_fl_str("{__recur:true,a:[",cg_args(args),"]}");;
const cg_match = (n)=>((()=>{let val=cg(_fl_get(n,"value"));let cases=_fl_get(n,"cases");let default_n=_fl_get(n,"defaultCase");let default_=((default_n==null)?"null":cg(default_n));let cases_js=match_cases_loop(cases,0,"");return _fl_str("((__v)=>{",cases_js,"return ",default_,";})(",val,")");})());;
const match_cases_loop = (cases,i,acc)=>((i>=_fl_length(cases))?acc:((()=>{let c=_fl_get(cases,i);let pat=_fl_get(c,"pattern");let body=cg(_fl_get(c,"body"));let guard_n=_fl_get(c,"guard");let test=pattern_test(pat,"__v");let bind=pattern_bindings(pat,"__v");let guard_js=((guard_n==null)?"true":cg(guard_n));let inner=((guard_n==null)?_fl_str(bind,"return ",body,";"):_fl_str(bind,"if(",guard_js,"){return ",body,";}"));return match_cases_loop(cases,(i+1),_fl_str(acc,"if(",test,"){",inner,"}"));})()));;
const pattern_test = (pat,v)=>((()=>{let k=_fl_get(pat,"kind");return ;})());;
const literal_to_js = (t,v)=>((t==="number")?v:((t==="string")?js_esc(v):((t==="symbol")?((v==="true")?"true":((v==="false")?"false":((v==="null")?"null":(true?js_esc(v):null)))):(true?"null":null))));;
const or_pattern_test = (pats,v,i,acc)=>((i>=_fl_length(pats))?((_fl_length(acc)===0)?"false":_fl_str("(",acc,")")):((()=>{let t=pattern_test(_fl_get(pats,i),v);return or_pattern_test(pats,v,(i+1),((_fl_length(acc)===0)?t:_fl_str(acc,"||",t)));})()));;
const pattern_bindings = (pat,v)=>((()=>{let k=_fl_get(pat,"kind");return ;})());;
const cg_compose = (args)=>_fl_str("((__x)=>",compose_nest(args,(_fl_length(args)-1),"__x"),")");;
const compose_nest = (args,i,acc)=>((i<0)?acc:((()=>{let f=_fl_str(cg(_fl_get(args,i)));return compose_nest(args,(i-1),_fl_str(f,"(",acc,")"));})()));;
const cg_pipe = (args)=>_fl_str("((__x)=>",pipe_nest(args,0,"__x"),")");;
const pipe_nest = (args,i,acc)=>((i>=_fl_length(args))?acc:((()=>{let f=_fl_str(cg(_fl_get(args,i)));return pipe_nest(args,(i+1),_fl_str(f,"(",acc,")"));})()));;
const cg_thread_first = (args)=>((()=>{let init=_fl_str(cg(_fl_get(args,0)));return thread_first_loop(args,1,init);})());;
const thread_first_loop = (args,i,acc)=>((i>=_fl_length(args))?acc:thread_first_loop(args,(i+1),thread_apply(_fl_get(args,i),acc,true)));;
const cg_thread_last = (args)=>((()=>{let init=_fl_str(cg(_fl_get(args,0)));return thread_last_loop(args,1,init);})());;
const thread_last_loop = (args,i,acc)=>((i>=_fl_length(args))?acc:thread_last_loop(args,(i+1),thread_apply(_fl_get(args,i),acc,false)));;
const thread_apply = (step,acc,fst)=>((_fl_get(step,"kind")==="sexpr")?((()=>{let op=js_name(_fl_get(step,"op"));let a=_fl_get(step,"args");return (fst?_fl_str(op,"(",acc,((_fl_length(a)===0)?"":_fl_str(",",cg_args(a))),")"):_fl_str(op,"(",((_fl_length(a)===0)?"":_fl_str(cg_args(a),",")),acc,")"));})()):(true?_fl_str(_fl_str(cg(step)),"(",acc,")"):null));;
const cg_call_form = (args)=>((()=>{let fn=_fl_str(cg(_fl_get(args,0)));let rest=_fl_slice(args,1,_fl_length(args));return _fl_str(fn,"(",cg_args(rest),")");})());;
const cg_async = (args)=>_fl_str("(async()=>{",cg_do_body(args,0,""),"})()");;
const cg_await = (args)=>_fl_str("(await ",cg(_fl_get(args,0)),")");;
const cg_defstruct = (args)=>((()=>{let name_n=_fl_get(args,0);let name=extract_name(name_n);let fields=_fl_slice(args,1,_fl_length(args));let params=struct_field_list(fields,0,"");let init=struct_init_list(fields,0,"");return _fl_str("const ",name," = (",params,")=>({__struct:\"",name,"\",",init,"})");})());;
const struct_field_list = (fs,i,acc)=>((i>=_fl_length(fs))?acc:((()=>{let n=extract_name(_fl_get(fs,i));return struct_field_list(fs,(i+1),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));;
const struct_init_list = (fs,i,acc)=>((i>=_fl_length(fs))?acc:((()=>{let n=extract_name(_fl_get(fs,i));return struct_init_list(fs,(i+1),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));;
const cg_args = (args)=>args_loop(args,0,"");;
const args_loop = (args,i,acc)=>((i>=_fl_length(args))?acc:((()=>{let c=_fl_str(cg(_fl_get(args,i)));return args_loop(args,(i+1),((i===0)?c:_fl_str(acc,",",c)));})()));;
const cg_binop = (args,op,zero)=>((_fl_length(args)===0)?zero:((_fl_length(args)===1)?_fl_str(cg(_fl_get(args,0))):(true?_fl_str("(",binop_loop(args,0,"",op),")"):null)));;
const binop_loop = (args,i,acc,op)=>((i>=_fl_length(args))?acc:((()=>{let c=_fl_str(cg(_fl_get(args,i)));return binop_loop(args,(i+1),((i===0)?c:_fl_str(acc,op,c)),op);})()));;
const cg_pair = (args,op)=>_fl_str("(",cg(_fl_get(args,0)),op,cg(_fl_get(args,1)),")");;
const cg_sub = (args)=>((_fl_length(args)===1)?_fl_str("(-",cg(_fl_get(args,0)),")"):_fl_str("(",cg(_fl_get(args,0)),"-",cg(_fl_get(args,1)),")"));;
const extract_name = (n)=>((_fl_get(n,"kind")==="variable")?js_name(_fl_get(n,"name")):((_fl_get(n,"kind")==="literal")?js_name(_fl_get(n,"value")):(true?"_anon":null)));;
const extract_params = (items)=>param_loop(items,0,"");;
const param_loop = (items,i,acc)=>((items==null)?acc:((i>=_fl_length(items))?acc:((()=>{let cur=_fl_get(items,i);let cur_val=((_fl_get(cur,"kind")==="literal")?_fl_get(cur,"value"):"");return ((cur_val==="&")?(((i+1)>=_fl_length(items))?acc:((()=>{let rest_name=extract_name(_fl_get(items,(i+1)));let entry=_fl_str("...",rest_name);return param_loop(items,(i+2),((i===0)?entry:_fl_str(acc,",",entry)));})())):((()=>{let name=extract_name(cur);return param_loop(items,(i+1),((i===0)?name:_fl_str(acc,",",name)));})()));})())));;
const cg_native = (op,args)=>((()=>{let as=cg_args(args);return ;})());;
const cg_call = (op,args)=>((()=>{let fn_name=js_name(((_fl_char_at(op,0)==="$")?_fl_substring(op,1,_fl_length(op)):op));return _fl_str(fn_name,"(",cg_args(args),")");})());;
const cg_sexpr = (n)=>((()=>{let op=_fl_get(n,"op");let args=_fl_get(n,"args");return ;})());;
const prelude_string = ()=>_fl_str("const _fl_str = (...xs) => xs.map(x => x==null?'null':String(x)).join('');","const _fl_length = (x) => (x==null ? 0 : x.length);","const _fl_substring = (s, a, b) => (b==null ? s.slice(a) : s.slice(a, b));","const _fl_char_at = (s, i) => (s[i] || null);","const _fl_replace = (s, a, b) => s.split(a).join(b);","const _fl_starts_with = (s, p) => s.startsWith(p);","const _fl_ends_with = (s, p) => s.endsWith(p);","const _fl_contains = (s, p) => s.includes(p);","const _fl_split = (s, sep) => s.split(sep);","const _fl_join = (l, sep) => l.join(sep==null?'':sep);","const _fl_trim = (s) => s.trim();","const _fl_upper = (s) => s.toUpperCase();","const _fl_lower = (s) => s.toLowerCase();","const _fl_repeat = (s, n) => s.repeat(n);","const _fl_index_of = (s, p) => s.indexOf(p);");;
const prelude_list = ()=>_fl_str("const _fl_first = (l) => (l==null || l.length===0 ? null : l[0]);","const _fl_last = (l) => (l==null || l.length===0 ? null : l[l.length-1]);","const _fl_rest = (l) => (l==null || l.length===0 ? [] : l.slice(1));","const _fl_append = (a, b) => (Array.isArray(b) ? [...a, ...b] : [...a, b]);","const _fl_slice = (l, a, b) => l.slice(a, b);","const _fl_map = (f, l) => l.map(x => f(x));","const _fl_filter = (f, l) => l.filter(x => f(x));","const _fl_reduce = (f, init, l) => l.reduce((acc, x) => f(acc, x), init);","const _fl_find = (f, l) => (l.find(x => f(x)) ?? null);","const _fl_every = (f, l) => l.every(x => f(x));","const _fl_some = (f, l) => l.some(x => f(x));","const _fl_sort = (l, cmp) => [...l].sort(cmp || ((a,b)=>a<b?-1:a>b?1:0));","const _fl_reverse = (l) => [...l].reverse();","const _fl_flatten = (l) => l.flat(Infinity);","const _fl_distinct = (l) => [...new Set(l)];","const _fl_range = (a, b, s) => { let r=[]; let step=s||1; for(let i=a;i<b;i+=step)r.push(i); return r; };","const _fl_take = (n, l) => l.slice(0, n);","const _fl_drop = (n, l) => l.slice(n);");;
const prelude_map = ()=>_fl_str("const _fl_get = (o, k) => (o==null ? null : (o[k]===undefined ? null : o[k]));","const _fl_keys = (o) => (o==null ? [] : Object.keys(o));","const _fl_values = (o) => (o==null ? [] : Object.values(o));","const _fl_entries = (o) => (o==null ? [] : Object.entries(o).map(([k,v])=>[k,v]));","const _fl_has_key = (o, k) => (o!=null && k in o);","const _fl_map_set = (o, k, v) => ({...o, [k]: v});","const _fl_map_delete = (o, k) => { const c={...o}; delete c[k]; return c; };","const _fl_merge = (...os) => Object.assign({}, ...os);","const _fl_is_map = (x) => (x!=null && typeof x==='object' && !Array.isArray(x));","const _fl_type_of = (x) => (x==null?'null':Array.isArray(x)?'list':typeof x);","const map_entries = (m) => m instanceof Map ? [...m.entries()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.entries(m) : []);","const map_keys = (m) => m instanceof Map ? [...m.keys()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.keys(m) : []);","const map_values = (m) => m instanceof Map ? [...m.values()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.values(m) : []);");;
const prelude_time_regex = ()=>_fl_str("const now = () => Date.now();","const now_ms = () => Date.now();","const now_iso = () => new Date().toISOString();","const now_unix = () => Math.floor(Date.now()/1000);","const regex_match = (s, p) => new RegExp(p).test(s);","const regex_find = (s, p) => { const m = s.match(new RegExp(p)); return m ? m[0] : null; };","const regex_find_all = (s, p) => s.match(new RegExp(p, 'g')) || [];","const regex_replace = (s, p, r) => s.replace(new RegExp(p, 'g'), r);","const regex_split = (s, p) => s.split(new RegExp(p));","const regex_count = (s, p) => (s.match(new RegExp(p, 'g')) || []).length;","const regex_extract = (s, p) => { const m = s.match(new RegExp(p)); return m ? m.slice(1) : []; };");;
const prelude_io_misc = ()=>_fl_str("const _fl_file_read = (p) => require('fs').readFileSync(p, 'utf8');","const _fl_file_write = (p, c) => require('fs').writeFileSync(p, c);","const _fl_file_exists = (p) => require('fs').existsSync(p);","const _fl_shell_capture = (cmd) => { try { const {execSync}=require('child_process'); return {stdout:execSync(cmd,{encoding:'utf8'}),stderr:'',code:0}; } catch(e) { return {stdout:'',stderr:String(e),code:1}; } };","const _fl_empty_q = (x) => (x==null || x.length===0);","const __argv__ = process.argv.slice(2);");;
const prelude_db_server = ()=>_fl_str("const _fl_pg_exec = (db,sql,...args) => null;","const _fl_pg_query = (db,sql,...args) => [];","const _fl_pg_connect = (cfg) => null;","const _fl_mariadb_exec = (db,sql,...args) => null;","const _fl_mariadb_query = (db,sql,...args) => [];","const _fl_mariadb_one = (db,sql,...args) => null;","const _fl_db_query = (path,sql,...args) => [];","const _fl_db_exec = (path,sql,...args) => null;","const _fl_server_post = (path,fn) => null;","const _fl_server_get = (path,fn) => null;","const _fl_server_put = (path,fn) => null;","const _fl_server_delete = (path,fn) => null;","const _fl_server_start = (port) => null;","const _fl_server_stop = () => null;","const _fl_http_get = (url) => '';","const _fl_http_post = (url,body) => '';","const _fl_ws_send = (sid,data) => null;");;
const prelude_parts = ()=>[prelude_string(),prelude_list(),prelude_map(),prelude_time_regex(),prelude_io_misc(),prelude_db_server()];;
const runtime_prelude = ()=>_fl_reduce(((acc,part)=>_fl_str(acc,part)),"",prelude_parts());;
const fl__gtjs_code = (ast)=>_fl_reduce(((acc,node)=>_fl_str(acc,cg(node),";\n")),"",ast);;
const fl__gtjs_with_prelude = (ast)=>((()=>{let p=runtime_prelude();return ((()=>{let c=fl__gtjs_code(ast);return _fl_str(p,"\n",c);})());})());;
const compile_file = (input,output)=>((()=>{let src=_fl_file_read(input);let tokens=lex(src);let ast=parse(tokens);let js=fl__gtjs_with_prelude(ast);_fl_file_write(output,js);return console.log(_fl_str("compiled ",input," -> ",output," size=",_fl_length(js)));})());;
((__argv__==null)?null:((_fl_length(__argv__)===0)?null:compile_file(_fl_get(__argv__,0),((_fl_length(__argv__)>=2)?_fl_get(__argv__,1):_fl_str(_fl_get(__argv__,0),".out.js")))));
const str_lines = (s)=>_fl_split(s,"\n");;
const str_words = (s)=>_fl_split(_fl_trim(s)," ");;
const str_join_lines = (lines)=>str_join_loop(lines,0,"");;
const str_join_loop = (lst,i,acc)=>((i>=_fl_length(lst))?acc:str_join_loop(lst,(i+1),((i===0)?_fl_get(lst,0):_fl_str(acc,"\n",_fl_get(lst,i)))));;
const str_count = (s,sub)=>((_fl_length(sub)===0)?0:str_count_loop(s,sub,0,0));;
const str_count_loop = (s,sub,pos,acc)=>((()=>{let rest=_fl_substring(s,pos,_fl_length(s));let idx=_fl_index_of(rest,sub);return ((idx<0)?acc:str_count_loop(s,sub,(pos+idx+_fl_length(sub)),(acc+1)));})());;
const csv_parse_line = (line)=>_fl_split(line,",");;
const csv_parse = (csv)=>((()=>{let lines=_fl_split(csv,"\n");return csv_parse_loop(lines,0,[]);})());;
const csv_parse_loop = (lines,i,acc)=>((i>=_fl_length(lines))?acc:csv_parse_loop(lines,(i+1),_fl_append(acc,csv_parse_line(_fl_get(lines,i)))));;
const str_repeat = (s,n)=>((n<=0)?"":str_repeat_loop(s,n,0,""));;
const str_repeat_loop = (s,n,i,acc)=>((i>=n)?acc:str_repeat_loop(s,n,(i+1),_fl_str(acc,s)));;
const data_json_parse = (s)=>JSON.parse(s);;
const data_json_str = (obj)=>JSON.stringify(obj);;
const data_json_pretty = (obj)=>JSON.stringify(obj);;
const to_query_string = (obj)=>to_query_loop(_fl_keys(obj),obj,0,[]);;
const to_query_loop = (ks,obj,i,acc)=>((i>=_fl_length(ks))?_fl_join(acc,"&"):((()=>{let k=_fl_get(ks,i);let v=_fl_get(obj,k);return to_query_loop(ks,obj,(i+1),_fl_append(acc,_fl_str(k,"=",v)));})()));;
const hash_simple = (s)=>hash_simple_loop(_fl_str(s),0,5381,0);;
const hash_simple_loop = (s,i,hash,max)=>((i>=_fl_length(s))?(Math.abs(hash)%2147483647):hash_simple_loop(s,(i+1),((hash*33)+char_code_at(s,i)),(i+1)));;
const hash_fnv1a = (s)=>((()=>{let fnv_offset=2166136261;let fnv_prime=16777619;return hash_fnv_loop(_fl_str(s),0,fnv_offset);})());;
const hash_fnv_loop = (s,i,hash)=>((i>=_fl_length(s))?(Math.abs(hash)%2147483647):hash_fnv_loop(s,(i+1),(bit_xor(hash,char_code_at(s,i))*16777619)));;
const hash_djb2 = (s)=>hash_djb_loop(_fl_str(s),0,5381);;
const hash_djb_loop = (s,i,hash)=>((i>=_fl_length(s))?(Math.abs(hash)%2147483647):hash_djb_loop(s,(i+1),((hash*33)+char_code_at(s,i))));;
const hash_object = (obj)=>hash_simple(JSON.stringify(obj));;
const hash_consistent = (s,seed)=>((()=>{let h=hash_simple(s);return (((h*seed)+seed)%2147483647);})());;
const now_s = ()=>Math.floor((now()/1000));;
const time_diff_ms = (t1,t2)=>(t2-t1);;
const time_elapsed = (start)=>(now()-start);;
const date_parts = (ts)=>({});;
const ts_to_s = (ts)=>Math.floor((ts/1000));;
const s_to_ts = (s)=>(s*1000);;
const time_ago = (ts)=>((()=>{let diff=(now()-ts);let s=Math.floor((diff/1000));let m=Math.floor((s/60));let h=Math.floor((m/60));let d=Math.floor((h/24));return ;})());;
const str_starts_with_q = (s,prefix)=>((_fl_length(prefix)>_fl_length(s))?false:(_fl_substring(s,0,_fl_length(prefix))===prefix));;
const str_ends_with_q = (s,suffix)=>((_fl_length(suffix)>_fl_length(s))?false:(_fl_substring(s,(_fl_length(s)-_fl_length(suffix)),_fl_length(s))===suffix));;
const str_repeat = (s,n)=>str_repeat_loop(s,n,"");;
const str_repeat_loop = (s,n,acc)=>((n<=0)?acc:str_repeat_loop(s,(n-1),_fl_str(acc,s)));;
const str_pad_left = (s,n,pad)=>((()=>{let diff=(n-_fl_length(s));return ((diff<=0)?s:_fl_str(str_repeat(pad,diff),s));})());;
const str_pad_right = (s,n,pad)=>((()=>{let diff=(n-_fl_length(s));return ((diff<=0)?s:_fl_str(s,str_repeat(pad,diff)));})());;
const file_read = (path)=>_fl_file_read(_fl_str(path));;
const file_write = (path,content)=>_fl_file_write(_fl_str(path),_fl_str(content));;
const file_append = (path,content)=>file_append(_fl_str(path),_fl_str(content));;
const file_exists_q = (path)=>_fl_file_exists(_fl_str(path));;
const file_delete = (path)=>file_delete(_fl_str(path));;
const file_copy = (src,dest)=>file_copy(_fl_str(src),_fl_str(dest));;
const file_rename = (old,new_)=>file_rename(_fl_str(old),_fl_str(new_));;
const file_size = (path)=>file_size(_fl_str(path));;
const file_modified = (path)=>file_modified(_fl_str(path));;
const file_json = (path)=>JSON.parse(_fl_file_read(_fl_str(path)));;
const file_json_write = (path,obj)=>_fl_file_write(_fl_str(path),JSON.stringify(obj));;
const file_lines = (path)=>str_lines(_fl_file_read(_fl_str(path)));;
const file_mkdir = (path)=>file_mkdir(_fl_str(path));;
const file_rmdir = (path)=>file_rmdir(_fl_str(path));;
const file_list = (path)=>file_list(_fl_str(path));;
const file_is_file_q = (path)=>file_is_file(_fl_str(path));;
const file_is_dir_q = (path)=>file_is_dir(_fl_str(path));;
const process_run = (cmd)=>process_run(_fl_str(cmd));;
const process_run_args = (cmd,args)=>process_run_args(_fl_str(cmd),args);;
const process_exec = (cmd)=>process_exec(_fl_str(cmd));;
const process_exec_args = (cmd,args)=>process_exec_args(_fl_str(cmd),args);;
const process_spawn = (cmd,args)=>process_spawn(_fl_str(cmd),args);;
const process_kill = (pid)=>process_kill(Math.floor(pid));;
const process_exists_q = (pid)=>process_exists(Math.floor(pid));;
const process_wait = (pid)=>process_wait(Math.floor(pid));;
const shell_run = (cmd)=>process_exec(_fl_str(cmd));;
const shell_pipe = (cmd1,cmd2)=>process_exec(_fl_str(cmd1," | ",cmd2));;
const env_get = (key)=>env_get(_fl_str(key));;
const env_set = (key,value)=>env_set(_fl_str(key),_fl_str(value));;
const env_all = ()=>env_all();;
const getcwd = ()=>process_getcwd();;
const chdir = (path)=>process_chdir(_fl_str(path));;
const pid = ()=>process_pid();;
const pid_parent = ()=>process_ppid();;
console.log("\n═══════════════════════════════════════════");
console.log("  FL Self-Hosted Compiler (Phase 28)");
console.log("═══════════════════════════════════════════\n");
((()=>{let input=_fl_get(__argv__,0);let output=_fl_get(__argv__,1);return (((input==null)||(output==null))?console.log("Usage: node bootstrap.js run self/main.fl <input.fl> <output.js>"):((()=>{let src=_fl_file_read(input);return ((()=>{let tokens=lex(src);return ((()=>{let ast=parse(tokens);return ((()=>{let js=fl__gtjs_with_prelude(ast);return (()=>{console.log(_fl_str("📖 ",input," → ",output));console.log(_fl_str("   Lexed: ",_fl_length(tokens)," tokens"));console.log(_fl_str("   Parsed: ",_fl_length(ast)," nodes"));console.log(_fl_str("   Generated: ",_fl_length(js)," bytes"));_fl_file_write(output,js);return console.log("✨ Success!");})();})());})());})());})()));})());
