const _fl_str = (...xs) => xs.map(x => x==null?'null':String(x)).join('');const _fl_length = (x) => (x==null ? 0 : x.length);const _fl_substring = (s, a, b) => (b==null ? s.slice(a) : s.slice(a, b));const _fl_char_at = (s, i) => (s[i] || null);const _fl_replace = (s, a, b) => s.split(a).join(b);const _fl_starts_with = (s, p) => s.startsWith(p);const _fl_ends_with = (s, p) => s.endsWith(p);const _fl_contains = (s, p) => s.includes(p);const _fl_split = (s, sep) => s.split(sep);const _fl_join = (l, sep) => l.join(sep==null?'':sep);const _fl_trim = (s) => s.trim();const _fl_upper = (s) => s.toUpperCase();const _fl_lower = (s) => s.toLowerCase();const _fl_repeat = (s, n) => s.repeat(n);const _fl_index_of = (s, p) => s.indexOf(p);const _fl_first = (l) => (l==null || l.length===0 ? null : l[0]);const _fl_last = (l) => (l==null || l.length===0 ? null : l[l.length-1]);const _fl_rest = (l) => (l==null || l.length===0 ? [] : l.slice(1));const _fl_append = (a, b) => (Array.isArray(b) ? [...a, ...b] : [...a, b]);const _fl_slice = (l, a, b) => l.slice(a, b);const _fl_map = (f, l) => l.map(x => f(x));const _fl_filter = (f, l) => l.filter(x => f(x));const _fl_reduce = (f, init, l) => l.reduce((acc, x) => f(acc, x), init);const _fl_find = (f, l) => (l.find(x => f(x)) ?? null);const _fl_every = (f, l) => l.every(x => f(x));const _fl_some = (f, l) => l.some(x => f(x));const _fl_sort = (l, cmp) => [...l].sort(cmp || ((a,b)=>a<b?-1:a>b?1:0));const _fl_reverse = (l) => [...l].reverse();const _fl_flatten = (l) => l.flat(Infinity);const _fl_distinct = (l) => [...new Set(l)];const _fl_range = (a, b, s) => { let r=[]; let step=s||1; for(let i=a;i<b;i+=step)r.push(i); return r; };const _fl_take = (n, l) => l.slice(0, n);const _fl_drop = (n, l) => l.slice(n);const _fl_get = (o, k) => (o==null ? null : (o[k]===undefined ? null : o[k]));const _fl_keys = (o) => (o==null ? [] : Object.keys(o));const _fl_values = (o) => (o==null ? [] : Object.values(o));const _fl_entries = (o) => (o==null ? [] : Object.entries(o).map(([k,v])=>[k,v]));const _fl_has_key = (o, k) => (o!=null && k in o);const _fl_map_set = (o, k, v) => ({...o, [k]: v});const _fl_map_delete = (o, k) => { const c={...o}; delete c[k]; return c; };const _fl_merge = (...os) => Object.assign({}, ...os);const _fl_is_map = (x) => (x!=null && typeof x==='object' && !Array.isArray(x));const _fl_type_of = (x) => (x==null?'null':Array.isArray(x)?'list':typeof x);const map_entries = (m) => m instanceof Map ? [...m.entries()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.entries(m) : []);const map_keys = (m) => m instanceof Map ? [...m.keys()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.keys(m) : []);const map_values = (m) => m instanceof Map ? [...m.values()] : (m && typeof m === 'object' && !Array.isArray(m) ? Object.values(m) : []);const _fl_file_read = (p) => require('fs').readFileSync(p, 'utf8');const _fl_file_write = (p, c) => require('fs').writeFileSync(p, c);const _fl_file_exists = (p) => require('fs').existsSync(p);const _fl_shell_capture = (cmd) => { try { const {execSync}=require('child_process'); return {stdout:execSync(cmd,{encoding:'utf8'}),stderr:'',code:0}; } catch(e) { return {stdout:'',stderr:String(e),code:1}; } };const _fl_empty_q = (x) => (x==null || x.length===0);const __argv__ = process.argv.slice(2);
const is_digit_q = ()=>((c==null)?false:((c>="0")&&(c<="9")));;
const is_alpha_q = ()=>((c==null)?false:(((c>="a")&&(c<="z"))||((c>="A")&&(c<="Z"))));;
const is_alnum_q = ()=>(is_digit_q(c)||is_alpha_q(c));;
const is_space_q = ()=>((c===" ")||(c==="\t")||(c==="\n")||(c==="\r"));;
const is_symbol_char_q = ()=>((c==null)?false:(is_alnum_q(c)||(c==="-")||(c==="_")||(c==="?")||(c==="!")||(c==="/")||(c===".")||(c==="<")||(c===">")||(c==="=")||(c==="+")||(c==="*")||(c==="%")||(c==="&")||(c==="|")||(c==="^")||(c==="~")));;
const make_state = ()=>({});;
const peek_at = ()=>((()=>{return ((i>=_fl_length(src))?null:_fl_char_at(src,i));})());;
const peek = ()=>peek_at(st,0);;
const at_end_q = ()=>(_fl_get(st,"idx")>=_fl_length(_fl_get(st,"src")));;
const advance = ()=>((()=>{return ((c==="\n")?({}):({}));})());;
const emit = ()=>({});;
const skip_comment = ()=>(at_end_q(st)?st:((()=>{return ((c==="\n")?advance(st):skip_comment(advance(st)));})()));;
const skip_ws = ()=>(at_end_q(st)?st:((()=>{return (null?null:(null?null:(null?null:null)));})()));;
const read_number_body = ()=>(at_end_q(st)?emit(st,"Number",acc,line,col):((()=>{return (null?null:(null?null:(null?null:null)));})()));;
const read_number = ()=>read_number_body(st,"",false,_fl_get(st,"line"),_fl_get(st,"col"));;
const translate_esc = ()=>(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:null))))));;
const read_string_body = ()=>(at_end_q(st)?emit(st,"String",acc,line,col):((()=>{return (null?null:(null?null:(null?null:null)));})()));;
const read_string = ()=>((()=>{return read_string_body(st1,"",line,col);})());;
const read_symbol_body_kind = ()=>(at_end_q(st)?emit(st,kind,acc,line,col):((()=>{return (is_symbol_char_q(c)?read_symbol_body_kind(advance(st),_fl_str(acc,c),line,col,kind):emit(st,kind,acc,line,col));})()));;
const read_symbol = ()=>read_symbol_body_kind(st,"",_fl_get(st,"line"),_fl_get(st,"col"),"Symbol");;
const read_variable = ()=>((()=>{return read_symbol_body_kind(st1,"",line,col,"Variable");})());;
const read_keyword = ()=>((()=>{return read_symbol_body_kind(st1,"",line,col,"Keyword");})());;
const read_token = ()=>((()=>{return (at_end_q(st1)?st1:((()=>{return (null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:(null?null:null)))))))))))));})()));})());;
const lex_loop = ()=>((()=>{return (at_end_q(st1)?_fl_get(st1,"tokens"):lex_loop(read_token(st1)));})());;
const lex = ()=>lex_loop(make_state(src));;
const make_literal = ()=>({});;
const make_variable = ()=>({});;
const make_keyword = ()=>({});;
const make_sexpr = ()=>({});;
const make_array_block = ()=>({});;
const make_map_block = ()=>({});;
const make_block = ()=>({});;
const p_make = ()=>({});;
const p_peek = ()=>((()=>{return ((i>=_fl_length(t))?null:_fl_get(t,i));})());;
const p_peek_at = ()=>((()=>{return ((i>=_fl_length(t))?null:_fl_get(t,i));})());;
const p_end_q = ()=>(_fl_get(p,"idx")>=_fl_length(_fl_get(p,"tokens")));;
const p_advance = ()=>({});;
const p_with_ast = ()=>({});;
const p_append_ast = ()=>p_with_ast(p,_fl_append(_fl_get(p,"ast"),[node]));;
const r_pair = ()=>({});;
const parse_atom = ()=>((()=>{return (null?null:(null?null:(null?null:(null?null:(null?null:(null?null:null))))));})());;
const parse_expr = ()=>((()=>{return (null?null:(null?null:(null?null:(null?null:null))));})());;
const parse_sexpr = ()=>((()=>{return ((_fl_length(args)===0)?r_pair(parse_consume_rparen(p2),make_sexpr("",[],line)):((()=>{return r_pair(parse_consume_rparen(p2),make_sexpr(op,rest,line));})()));})());;
const parse_consume_rparen = ()=>((()=>{return (((!(t==null))&&(_fl_get(t,"kind")==="RParen"))?p_advance(p):p);})());;
const parse_args = ()=>((()=>{return (null?null:(null?null:(null?null:(null?null:(null?null:null)))));})());;
const parse_bracket = ()=>((()=>{return (((!(next==null))&&(_fl_get(next,"kind")==="Symbol")&&is_block_type_q(_fl_get(next,"value"))&&(_fl_get(next,"value")===upper_case(_fl_get(next,"value"))))?parse_named_block(p1,line):parse_array(p1,line));})());;
const is_block_type_q = ()=>((()=>{return ((c>="A")&&(c<="Z"));})());;
const upper_case = ()=>s;;
const parse_array = ()=>((()=>{return r_pair(parse_consume_rbracket(p2),make_array_block(items,line));})());;
const parse_consume_rbracket = ()=>((()=>{return (((!(t==null))&&(_fl_get(t,"kind")==="RBracket"))?p_advance(p):p);})());;
const parse_named_block = ()=>((()=>{return r_pair(parse_consume_rbracket(p3),make_block(type,name,fields,line));})());;
const parse_optional_name = ()=>((()=>{return (((!(t==null))&&(_fl_get(t,"kind")==="Symbol")&&(!(_fl_char_at(_fl_get(t,"value"),0)===":")))?r_pair(p_advance(p),_fl_get(t,"value")):r_pair(p,null));})());;
const parse_block_fields = ()=>((()=>{return (null?null:(null?null:(null?null:(null?null:null))));})());;
const parse_map = ()=>((()=>{return r_pair(parse_consume_rbrace(p2),make_map_block(items,line));})());;
const parse_consume_rbrace = ()=>((()=>{return (((!(t==null))&&(_fl_get(t,"kind")==="RBrace"))?p_advance(p):p);})());;
const parse_all = ()=>(p_end_q(p)?_fl_get(p,"ast"):((()=>{return parse_all(p2);})()));;
const parse = ()=>parse_all(p_make(tokens));;
const src = "[FUNC f :params [$x] :body (* $x 2)]";
const toks = lex(src);
console.log("toks-len:",_fl_length(toks));
const ast = parse(toks);
const n = _fl_get(ast,0);
console.log("n.type:",_fl_get(n,"type"));
console.log("n.fields:",_fl_get(n,"fields"));
const f = _fl_get(n,"fields");
const pnode = _fl_get(f,"params");
console.log("pnode:",pnode);
const pf = _fl_get(pnode,"fields");
const pitems = _fl_get(pf,"items");
console.log("pitems-len:",_fl_length(pitems));
const p0 = _fl_get(pitems,0);
console.log("p0:",p0);
console.log("p0.kind:",_fl_get(p0,"kind"));
console.log("p0.name:",_fl_get(p0,"name"));
