const _fl_str = (...xs) => xs.map(x => x==null?'':String(x)).join('');
const _fl_length = (x) => (x?x.length:0);
const _fl_get = (o,k,d) => { if(o==null)return d||null; let ks=String(k).startsWith(':')?k.slice(1):String(k); if(Array.isArray(o)){let idx=parseInt(ks);if(!isNaN(idx))return o[idx]!==undefined?o[idx]:(d||null);if(ks==='length')return o.length;} if(typeof o==='object'){if(o[ks]!==undefined)return o[ks];} return d||null; }
const _fl_null_q = (v) => v===null||v===undefined;
const _fl_keys = (o) => o?Object.keys(o):[];
const _fl_map_set = (o,k,v) => ({...o,[k]:v});
const _fl_has_key_q = (o,k) => o?(String(k) in o):false;
const _fl_append = (l,x) => [...(l||[]),x];
const list = (...args) => [...args];
const append = (l,x) => [...(l||[]),x];
const _fl_first = (l) => (l&&l.length>0)?l[0]:null;
const _fl_last = (l) => (l&&l.length>0)?l[l.length-1]:null;
const _fl_rest = (l) => (l&&l.length>0)?l.slice(1):[];
const _fl_slice = (l,a,b) => (l||[]).slice(a,b);
const _fl_map = (arr,fn) => (arr||[]).map(x=>fn(x));
const _fl_filter = (arr,fn) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const _fl_reduce = (arr,fn,init) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const _fl_some = (f,l) => (l||[]).some(x=>f(x));
const _fl_every = (f,l) => (l||[]).every(x=>f(x));
const _fl_file_read = (p) => require('fs').readFileSync(p,'utf8');
const _fl_file_write = (p,c) => require('fs').writeFileSync(p,c);
const _fl_file_exists = (p) => require('fs').existsSync(p);
const _fl_file_delete = (p) => { try { require('fs').unlinkSync(p); } catch(e) {} };
const _fl_file_append = (p,c) => require('fs').appendFileSync(p,String(c));
const _fl_file_copy = (s,d) => require('fs').copyFileSync(s,d);
const _fl_file_rename = (o,n) => require('fs').renameSync(o,n);
const _fl_file_size = (p) => { try { return require('fs').statSync(p).size; } catch(e) { return 0; } };
const _fl_file_modified = (p) => { try { return require('fs').statSync(p).mtimeMs; } catch(e) { return 0; } };
const _fl_file_mkdir = (p) => { try { require('fs').mkdirSync(p,{recursive:true}); } catch(e) {} };
const _fl_file_rmdir = (p) => { try { require('fs').rmSync(p,{recursive:true,force:true}); } catch(e) {} };
const _fl_file_list = (p) => { try { return require('fs').readdirSync(p); } catch(e) { return []; } };
const _fl_process_run = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_run_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_spawn = (cmd,args) => { try { const r=require('child_process').spawnSync(cmd,args||[],{encoding:'utf8'}); return r.stdout||''; } catch(e) { return ''; } };
const _fl_process_kill = (pid) => { try { process.kill(pid); } catch(e) {} };
const _fl_process_wait = (pid) => null;
const _fl_env_get = (k) => process.env[k]||null;
const _fl_env_set = (k,v) => { process.env[k]=String(v); };
const _fl_env_all = () => process.env;
const _fl_file_is_file = (p) => { try { return require('fs').statSync(p).isFile(); } catch(e) { return false; } };
const _fl_file_is_dir = (p) => { try { return require('fs').statSync(p).isDirectory(); } catch(e) { return false; } };
const _fl_process_exists = (pid) => { try { process.kill(pid,0); return true; } catch(e) { return false; } };
const _fl_process_getcwd = () => process.cwd();
const _fl_process_chdir = (p) => { try { process.chdir(p); } catch(e) {} };
const _fl_process_pid = () => process.pid;
const _fl_process_ppid = () => process.ppid||null;
const file_read = (p) => _fl_file_read(String(p));
const file_write = (p,c) => _fl_file_write(String(p),String(c));
const file_exists = (p) => _fl_file_exists(String(p));
const _fl_get_argv = () => (typeof process!=='undefined'?process.argv.slice(2):[]);
const _fl_print = (v) => { console.log(v); return v; }
const null_q = _fl_null_q;
const some_q = _fl_some;
const every_q = _fl_every;
const cli_args = _fl_get_argv;
const get = _fl_get;
const keys = _fl_keys;
const has_key_q = _fl_has_key_q;
const slice = _fl_slice;
const first = _fl_first;
const last = _fl_last;
const rest = _fl_rest;
const map = (fn,arr) => (arr||[]).map(x=>fn(x));
const filter = (fn,arr) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const reduce = (fn,init,arr) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const print = _fl_print;
const println = (v) => { console.log(v==null?'':String(v)); return v; }
const str_replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const str_index_of = (s,sub) => (typeof s==='string'&&typeof sub==='string')?s.indexOf(sub):-1;
const index_of = str_index_of;
const str_slice = (s,a,b) => s?(b===undefined?s.slice(a):s.slice(a,b)):'';
const substring = str_slice;
const char_at = (s,i) => (s&&s[i])||null;
const char_code_at = (s,i) => typeof s==='string'?s.charCodeAt(i):0;
const trim = (s) => String(s||'').trim();
const starts_with_q = (s,p) => String(s||'').startsWith(String(p||''));
const ends_with_q = (s,sf) => String(s||'').endsWith(String(sf||''));
const replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); if(ov instanceof RegExp)return st.replace(ov,nv==null?'':String(nv)); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const split = (s,sep) => String(s||'').split(sep);
const str_join = (arr,sep) => (arr||[]).join(sep===undefined?'':sep);
const join = str_join;
const concat = (a,b) => (Array.isArray(a)&&Array.isArray(b))?[...a,...b]:String(a||'')+String(b||'');
const push = (arr,v) => [...(arr||[]),v];
const pop = (arr) => (arr&&arr.length>0)?arr.slice(0,-1):[];
const reverse = (arr) => Array.isArray(arr)?[...arr].reverse():arr;
const sort_by = (arr,fn) => Array.isArray(arr)?[...arr].sort((a,b)=>fn(a)<fn(b)?-1:fn(a)>fn(b)?1:0):arr;
const flat_map = (arr,fn) => (arr||[]).flatMap(fn);
const range = (s,e) => { const r=[]; let st=e===undefined?0:s; let en=e===undefined?s:e; for(let i=st;i<en;i++)r.push(i); return r; };
const merge = (a,b) => Object.assign({},a,b);
const assoc = (o,k,v) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); r[key]=v; return r; };
const dissoc = (o,k) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); delete r[key]; return r; };
var map_entries = (m) => m instanceof Map?[...m.entries()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.entries(m):[]);
var map_keys = (m) => m instanceof Map?[...m.keys()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.keys(m):[]);
var map_values = (m) => m instanceof Map?[...m.values()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.values(m):[]);
const array_q = (v) => Array.isArray(v);
var list_q = (v) => Array.isArray(v);
var map_q = (v) => v!==null&&typeof v==='object'&&!Array.isArray(v);
var fn_q = (v) => typeof v==='function';
const number_q = (v) => typeof v==='number';
const string_q = (v) => typeof v==='string';
var str_upper = (s) => String(s||'').toUpperCase();
var str_lower = (s) => String(s||'').toLowerCase();
var str_contains = (s,sub) => String(s||'').includes(String(sub||''));
var str_starts_with = (s,p) => String(s||'').startsWith(String(p||''));
var str_ends_with = (s,sf) => String(s||'').endsWith(String(sf||''));
var str_trim = (s) => String(s||'').trim();
var str_length = (s) => String(s||'').length;
var str_split = (s,sep) => String(s||'').split(sep);
var take = (n,arr) => (arr||[]).slice(0,n);
var drop = (n,arr) => (arr||[]).slice(n);
var zip = (a,b) => { const r=[]; const l=Math.min((a||[]).length,(b||[]).length); for(let i=0;i<l;i++)r.push([a[i],b[i]]); return r; };
var flatten = (arr) => (arr||[]).flat();
var sort = (arr,fn) => fn?[...(arr||[])].sort((a,b)=>fn(a,b)?-1:1):[...(arr||[])].sort();
var math_sqrt = (n) => Math.sqrt(n);
var math_pi = Math.PI;
var unknown = (...a) => a[a.length-1];
function _fl_type_of(v) { if(v===null||v===undefined)return 'nil'; if(Array.isArray(v))return 'list'; return typeof v; }
const not = (v) => !v;
const abs = (n) => Math.abs(n);
const floor = (n) => Math.floor(n);
const ceil_val = (n) => Math.ceil(n);
const round = (n) => Math.round(n);
const max_val = (a,b) => a>b?a:b;
const min_val = (a,b) => a<b?a:b;
const error = (msg) => { throw new Error(String(msg)); };
const now_ms = () => Date.now();
const now_iso = () => new Date().toISOString();
const now_unix = () => Math.floor(Date.now()/1000);
const json_parse = (s) => { try{return JSON.parse(s);}catch(e){return null;} };
const json_stringify = (v) => JSON.stringify(v);
const shell_exec = (cmd,inp) => { try{const {execSync}=require('child_process');const opts={encoding:'utf8'};if(inp)opts.input=inp;return execSync(cmd,opts);}catch(e){return '';} };
const _fl_run_inherit = (cmd) => { require('child_process').spawnSync(cmd,{shell:true,stdio:'inherit'}); };
const __fl_routes = [];
const _fl_server_get = (path,fn) => { __fl_routes.push({method:'GET',path,fn}); };
const _fl_server_start = (port) => { const http=require('http'); http.createServer(async(req,res)=>{ const r=__fl_routes.find(r=>r.method===req.method&&r.path===require('url').parse(req.url).pathname); if(r){const result=await(typeof r.fn==='string'?eval(r.fn):r.fn)(req);res.end(String(result));}else{res.statusCode=404;res.end('Not Found');} }).listen(port);console.log('Server on '+port); };
const server_get = _fl_server_get;
const server_start = _fl_server_start;
var is_digit_q = (c) => (null_q(c)?false:((c>="0")&&(c<="9")));
var is_alpha_q = (c) => (null_q(c)?false:(((c>="a")&&(c<="z"))||((c>="A")&&(c<="Z"))));
var is_alnum_q = (c) => (is_digit_q(c)||is_alpha_q(c));
var is_space_q = (c) => ((c===" ")||(c==="\t")||(c==="\n")||(c==="\r"));
var is_symbol_char_q = (c) => (null_q(c)?false:(is_alnum_q(c)||(c==="-")||(c==="_")||(c==="?")||(c==="!")||(c==="/")||(c===".")||(c==="<")||(c===">")||(c==="=")||(c==="+")||(c==="*")||(c==="%")||(c==="&")||(c==="|")||(c==="^")||(c==="~")));
var make_state = (src) => ({"src":src,"idx":0,"line":1,"col":1,"tokens":[]});
var peek_at = (st,offset) => ((()=>{let src=get(st,"src");let i=(get(st,"idx")+offset);return ((i>=_fl_length(src))?null:char_at(src,i));})());
var peek = (st) => peek_at(st,0);
var at_end_q = (st) => (get(st,"idx")>=_fl_length(get(st,"src")));
var advance = (st) => ((()=>{let c=peek(st);return ((c==="\n")?({"src":get(st,"src"),"idx":(get(st,"idx")+1),"line":(get(st,"line")+1),"col":1,"tokens":get(st,"tokens")}):({"src":get(st,"src"),"idx":(get(st,"idx")+1),"line":get(st,"line"),"col":(get(st,"col")+1),"tokens":get(st,"tokens")}));})());
var emit = (st,kind,value,sl,sc) => ({"src":get(st,"src"),"idx":get(st,"idx"),"line":get(st,"line"),"col":get(st,"col"),"tokens":append(get(st,"tokens"),({"kind":kind,"type":kind,"value":value,"line":sl,"col":sc}))});
var skip_comment_loop = (cur) => ((at_end_q(cur)||(peek(cur)==="\n"))?(at_end_q(cur)?cur:advance(cur)):skip_comment_loop(advance(cur)));
var skip_comment = (st) => skip_comment_loop(st);
var skip_ws_loop = (cur) => (at_end_q(cur)?cur:((()=>{let c=peek(cur);return (is_space_q(c)?skip_ws_loop(advance(cur)):((c===";")?skip_ws_loop(skip_comment(cur)):(true?cur:null)));})()));
var skip_ws = (st) => skip_ws_loop(st);
var read_number_iter = (cur,res_acc,dot,line,col) => (at_end_q(cur)?emit(cur,"Number",res_acc,line,col):((()=>{let c=peek(cur);return (is_digit_q(c)?read_number_iter(advance(cur),_fl_str(res_acc,c),dot,line,col):(((c===".")&&not(dot))?read_number_iter(advance(cur),_fl_str(res_acc,c),true,line,col):(true?emit(cur,"Number",res_acc,line,col):null)));})()));
var read_number_body = (st,acc,has_dot,line,col) => read_number_iter(st,acc,has_dot,line,col);
var read_number = (st) => read_number_body(st,"",false,get(st,"line"),get(st,"col"));
var translate_esc = (c) => ((c==="n")?"\n":((c==="t")?"\t":((c==="r")?"\r":((c==="\"")?"\"":((c==="\\")?"\\":(true?c:null))))));
var read_string_iter = (cur,res_acc,line,col) => (at_end_q(cur)?emit(cur,"String",res_acc,line,col):((()=>{let c=peek(cur);return ((c==="\"")?emit(advance(cur),"String",res_acc,line,col):((c==="\\")?((()=>{let st2=advance(cur);let c2=peek(st2);return read_string_iter(advance(st2),_fl_str(res_acc,translate_esc(c2)),line,col);})()):(true?read_string_iter(advance(cur),_fl_str(res_acc,c),line,col):null)));})()));
var read_string_body = (st,acc,line,col) => read_string_iter(st,acc,line,col);
var read_string = (st) => ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_string_body(st1,"",line,col);})());
var read_symbol_iter = (cur,res_acc,line,col,kind) => (at_end_q(cur)?emit(cur,kind,res_acc,line,col):((()=>{let c=peek(cur);return (is_symbol_char_q(c)?read_symbol_iter(advance(cur),_fl_str(res_acc,c),line,col,kind):emit(cur,kind,res_acc,line,col));})()));
var read_symbol_body_kind = (st,acc,line,col,kind) => read_symbol_iter(st,acc,line,col,kind);
var read_symbol = (st) => read_symbol_body_kind(st,"",get(st,"line"),get(st,"col"),"Symbol");
var read_variable = (st) => ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Variable");})());
var read_keyword = (st) => ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Keyword");})());
var read_token = (st) => ((()=>{let st1=skip_ws(st);return (at_end_q(st1)?st1:((()=>{let c=peek(st1);let line=get(st1,"line");let col=get(st1,"col");return ((c==="(")?emit(advance(st1),"LParen",c,line,col):((c===")")?emit(advance(st1),"RParen",c,line,col):((c==="[")?emit(advance(st1),"LBracket",c,line,col):((c==="]")?emit(advance(st1),"RBracket",c,line,col):((c==="{")?emit(advance(st1),"LBrace",c,line,col):((c==="}")?emit(advance(st1),"RBrace",c,line,col):((c==="\"")?read_string(st1):((c==="$")?read_variable(st1):((c===":")?read_keyword(st1):(is_digit_q(c)?read_number(st1):(((c==="-")&&is_digit_q(peek_at(st1,1)))?read_number_body(advance(st1),"-",false,line,col):(is_symbol_char_q(c)?read_symbol(st1):(true?emit(advance(st1),"Unknown",c,line,col):null)))))))))))));})()));})());
var lex_loop = (cur) => ((()=>{let ws=skip_ws(cur);return (at_end_q(ws)?get(ws,"tokens"):lex_loop(read_token(ws)));})());
var lex = (src) => lex_loop(make_state(src));
var make_literal = (type,value,line) => ({"kind":"literal","type":type,"value":value,"line":line});
var make_variable = (name,line) => ({"kind":"variable","name":name,"line":line});
var make_keyword = (name,line) => ({"kind":"keyword","name":name,"line":line});
var make_sexpr = (op,args,line) => ({"kind":"sexpr","op":op,"args":args,"line":line});
var make_number = (v,line) => make_literal("number",v,line);
var make_string = (v,line) => make_literal("string",v,line);
var make_bool = (v,line) => make_literal("boolean",v,line);
var make_null = (line) => make_literal("null",null,line);
var make_symbol = (v,line) => make_literal("symbol",v,line);
var make_block = (type,name,fields,line) => ({"kind":"block","type":type,"name":name,"fields":fields,"line":line});
var make_array_block = (items,line) => make_block("Array",null,({"items":items}),line);
var make_map_block = (items,line) => make_block("Map",null,({"items":items}),line);
var make_pattern_literal = (value,line) => ({"kind":"pattern-literal","value":value,"line":line});
var make_pattern_variable = (name,line) => ({"kind":"pattern-variable","name":name,"line":line});
var make_pattern_wildcard = (line) => ({"kind":"pattern-wildcard","line":line});
var make_pattern_list = (items,rest,line) => ({"kind":"pattern-list","items":items,"rest":rest,"line":line});
var make_pattern_struct = (type_name,fields,line) => ({"kind":"pattern-struct","type":type_name,"fields":fields,"line":line});
var make_pattern_or = (alternatives,line) => ({"kind":"pattern-or","alternatives":alternatives,"line":line});
var make_pattern_range = (start,end,line) => ({"kind":"pattern-range","start":start,"end":end,"line":line});
var make_pattern_match = (value,cases,line) => ({"kind":"pattern-match","value":value,"cases":cases,"line":line});
var make_match_case = (pattern,guard,body,line) => ({"kind":"match-case","pattern":pattern,"guard":guard,"body":body,"line":line});
var make_function_value = (params,body,captured_env,name) => ({"kind":"function-value","params":params,"body":body,"capturedEnv":captured_env,"name":name});
var make_type_class = (name,generics,methods,line) => ({"kind":"type-class","name":name,"generics":generics,"methods":methods,"line":line});
var make_type_class_instance = (class_name,type_name,impls,line) => ({"kind":"type-class-instance","class":class_name,"type":type_name,"impls":impls,"line":line});
var make_module_block = (name,exports,body,line) => ({"kind":"module","name":name,"exports":exports,"body":body,"line":line});
var make_import_block = (path,alias,names,line) => ({"kind":"import","path":path,"alias":alias,"names":names,"line":line});
var make_open_block = (module_name,line) => ({"kind":"open","module":module_name,"line":line});
var make_search_block = (query,fields,line) => ({"kind":"search-block","query":query,"fields":fields,"line":line});
var make_learn_block = (topic,fields,line) => ({"kind":"learn-block","topic":topic,"fields":fields,"line":line});
var make_reasoning_block = (name,fields,line) => ({"kind":"reasoning-block","name":name,"fields":fields,"line":line});
var make_async_function = (name,params,body,line) => ({"kind":"async-function","name":name,"params":params,"body":body,"line":line});
var make_await = (expr,line) => ({"kind":"await","expr":expr,"line":line});
var make_try = (body,catch_,finally_,line) => ({"kind":"try","body":body,"catch":catch_,"finally":finally_,"line":line});
var make_catch = (param,body,line) => ({"kind":"catch","param":param,"body":body,"line":line});
var make_throw = (expr,line) => ({"kind":"throw","expr":expr,"line":line});
var make_template_string = (parts,expressions,line) => ({"kind":"template-string","parts":parts,"expressions":expressions,"line":line});
var make_loop = (init,condition,update,body,line) => ({"kind":"loop","init":init,"condition":condition,"update":update,"body":body,"line":line});
var make_page = (name,path,fields,line) => ({"kind":"page","name":name,"path":path,"fields":fields,"line":line});
var make_route = (method,path,handler,line) => ({"kind":"route","method":method,"path":path,"handler":handler,"line":line});
var make_component = (name,fields,line) => ({"kind":"component","name":name,"fields":fields,"line":line});
var make_form = (name,fields,line) => ({"kind":"form","name":name,"fields":fields,"line":line});
var deep_equal_q = (a,b) => ((null_q(a)&&null_q(b))?true:((null_q(a)||null_q(b))?false:((list_q(a)&&list_q(b))?deep_equal_list_q(a,b,0):((map_q(a)&&map_q(b))?deep_equal_map_q(a,b):(true?(a===b):null)))));
var deep_equal_list_q = (a,b,i) => (not((_fl_length(a)===_fl_length(b)))?false:((i>=_fl_length(a))?true:(not(deep_equal_q(get(a,i),get(b,i)))?false:(true?deep_equal_list_q(a,b,(i+1)):null))));
var deep_equal_map_q = (a,b) => ((()=>{let ka=keys_no_line(a);let kb=keys_no_line(b);return (not((_fl_length(ka)===_fl_length(kb)))?false:deep_equal_map_keys_q(a,b,ka,0));})());
var keys_no_line = (m) => filter(((k) => not((k==="line"))),json_keys(m));
var deep_equal_map_keys_q = (a,b,ks,i) => ((i>=_fl_length(ks))?true:(((()=>{let k=get(ks,i);return not(deep_equal_q(get(a,k),get(b,k)));})())?false:(true?deep_equal_map_keys_q(a,b,ks,(i+1)):null)));
var json_keys = (m) => obj_keys(m);
var p_make = (tokens) => ({"tokens":tokens,"idx":0,"ast":[]});
var p_peek = (p) => ((()=>{let i=get(p,"idx");let t=get(p,"tokens");return ((i>=_fl_length(t))?null:get(t,i));})());
var p_peek_at = (p,offset) => ((()=>{let i=(get(p,"idx")+offset);let t=get(p,"tokens");return ((i>=_fl_length(t))?null:get(t,i));})());
var p_end_q = (p) => (get(p,"idx")>=_fl_length(get(p,"tokens")));
var p_advance = (p) => ({"tokens":get(p,"tokens"),"idx":(get(p,"idx")+1),"ast":get(p,"ast")});
var p_with_ast = (p,ast) => ({"tokens":get(p,"tokens"),"idx":get(p,"idx"),"ast":ast});
var p_append_ast = (p,node) => p_with_ast(p,append(get(p,"ast"),node));
var r_pair = (p,node) => ({"p":p,"node":node});
var string_contains_q = (s,substr) => not((-1===str_index_of(s,substr)));
var parse_atom = (p) => ((()=>{let t=p_peek(p);let k=get(t,"kind");let v=get(t,"value");let line=get(t,"line");return ((k==="Number")?r_pair(p_advance(p),make_literal("number",v,line)):((k==="String")?(string_contains_q(v,_fl_str("$","{"))?r_pair(p_advance(p),make_template_string(v,list(),line)):r_pair(p_advance(p),make_literal("string",v,line))):((k==="Symbol")?r_pair(p_advance(p),make_literal("symbol",v,line)):((k==="Variable")?r_pair(p_advance(p),make_variable(v,line)):((k==="Keyword")?r_pair(p_advance(p),make_keyword(v,line)):(true?r_pair(p_advance(p),make_literal("unknown",v,line)):null))))));})());
var parse_expr = (p) => ((()=>{let t=p_peek(p);let k=get(t,"kind");return ((k==="LParen")?parse_sexpr(p):((k==="LBracket")?parse_bracket(p):((k==="LBrace")?parse_map(p):(true?parse_atom(p):null))));})());
var parse_sexpr = (p) => ((()=>{let start_tok=p_peek(p);let line=get(start_tok,"line");let p1=p_advance(p);let first=parse_args(p1,[]);let p2=get(first,"p");let args=get(first,"node");return ((_fl_length(args)===0)?r_pair(parse_consume_rparen(p2),make_sexpr("",list(),line)):((()=>{let op_node=get(args,0);let op=((get(op_node,"kind")==="literal")?get(op_node,"value"):((get(op_node,"kind")==="variable")?_fl_str("$",get(op_node,"name")):"unknown"));let rest=slice(args,1,_fl_length(args));return ((op==="try")?((()=>{let body=((_fl_length(rest)>0)?get(rest,0):null);let catch_clause=((_fl_length(rest)>1)?get(rest,1):null);let finally_clause=((_fl_length(rest)>2)?get(rest,2):null);return r_pair(parse_consume_rparen(p2),make_try(body,catch_clause,finally_clause,line));})()):((op==="loop")?((()=>{let loop_array=((_fl_length(rest)>0)?get(rest,0):null);let body_start=((_fl_length(rest)>1)?get(rest,1):null);return (null_q(loop_array)?r_pair(parse_consume_rparen(p2),make_sexpr("loop",list(),line)):(not((get(loop_array,"kind")==="array"))?r_pair(parse_consume_rparen(p2),make_sexpr("loop",rest,line)):((()=>{let items=get(loop_array,"items");let init=((_fl_length(items)>0)?get(items,0):null);let condition=((_fl_length(items)>1)?get(items,1):null);let update=((_fl_length(items)>2)?get(items,2):null);let body_exprs=slice(rest,1,_fl_length(rest));return r_pair(parse_consume_rparen(p2),make_loop(init,condition,update,((_fl_length(body_exprs)===1)?get(body_exprs,0):make_sexpr("do",body_exprs,line)),line));})())));})()):(true?r_pair(parse_consume_rparen(p2),make_sexpr(op,rest,line)):null)));})()));})());
var parse_consume_rparen = (p) => ((()=>{let t=p_peek(p);return ((not(null_q(t))&&(get(t,"kind")==="RParen"))?p_advance(p):p);})());
var parse_args = (p,acc) => ((()=>{let t=p_peek(p);return (null_q(t)?r_pair(p,acc):((get(t,"kind")==="RParen")?r_pair(p,acc):((get(t,"kind")==="RBracket")?r_pair(p,acc):((get(t,"kind")==="RBrace")?r_pair(p,acc):(true?((()=>{let one=parse_expr(p);return parse_args(get(one,"p"),append(acc,get(one,"node")));})()):null)))));})());
var parse_bracket = (p) => ((()=>{let tok=p_peek(p);let line=get(tok,"line");let p1=p_advance(p);let next=p_peek(p1);return ((not(null_q(next))&&(get(next,"kind")==="Symbol")&&is_block_type_q(get(next,"value"))&&(get(next,"value")===upper_case(get(next,"value"))))?parse_named_block(p1,line):parse_array(p1,line));})());
var is_block_type_q = (s) => ((()=>{let c=char_at(s,0);return ((c>="A")&&(c<="Z"));})());
var upper_case = (s) => s;
var parse_array = (p,line) => ((()=>{let collected=parse_args(p,[]);let p2=get(collected,"p");let items=get(collected,"node");return r_pair(parse_consume_rbracket(p2),make_array_block(items,line));})());
var parse_consume_rbracket = (p) => ((()=>{let t=p_peek(p);return ((not(null_q(t))&&(get(t,"kind")==="RBracket"))?p_advance(p):p);})());
var parse_named_block = (p,line) => ((()=>{let type_tok=p_peek(p);let type=get(type_tok,"value");let p1=p_advance(p);let name_info=parse_optional_name(p1);let p2=get(name_info,"p");let name=get(name_info,"node");let fields_info=parse_block_fields(p2,({}));let p3=get(fields_info,"p");let fields=get(fields_info,"node");return r_pair(parse_consume_rbracket(p3),make_block(type,name,fields,line));})());
var parse_optional_name = (p) => ((()=>{let t=p_peek(p);return ((not(null_q(t))&&(get(t,"kind")==="Symbol")&&not((char_at(get(t,"value"),0)===":")))?r_pair(p_advance(p),get(t,"value")):r_pair(p,null));})());
var parse_block_fields = (p,acc) => (p_end_q(p)?r_pair(p,acc):((()=>{let t=p_peek(p);return ((get(t,"kind")==="Keyword")?((()=>{let key=get(t,"value");let p1=p_advance(p);let val=parse_expr(p1);return parse_block_fields(get(val,"p"),_fl_map_set(acc,key,get(val,"node")));})()):r_pair(p,acc));})()));
var parse_map = (p) => ((()=>{let tok=p_peek(p);let line=get(tok,"line");let p1=p_advance(p);let collected=parse_args(p1,[]);let p2=get(collected,"p");let items=get(collected,"node");return r_pair(parse_consume_rbrace(p2),make_map_block(items,line));})());
var parse_consume_rbrace = (p) => ((()=>{let t=p_peek(p);return ((not(null_q(t))&&(get(t,"kind")==="RBrace"))?p_advance(p):p);})());
var parse_all = (p) => (p_end_q(p)?get(p,"ast"):((()=>{let one=parse_expr(p);let p2=p_append_ast(get(one,"p"),get(one,"node"));return parse_all(p2);})()));
var parse = (tokens) => parse_all(p_make(tokens));
var js_reserved_q = (n) => ((n==="default")||(n==="class")||(n==="const")||(n==="let")||(n==="if")||(n==="else")||(n==="switch")||(n==="case")||(n==="break")||(n==="continue")||(n==="for")||(n==="while")||(n==="function")||(n==="return")||(n==="throw")||(n==="try")||(n==="catch")||(n==="new")||(n==="delete")||(n==="typeof")||(n==="instanceof")||(n==="var")||(n==="in")||(n==="of")||(n==="this")||(n==="super")||(n==="void")||(n==="yield")||(n==="async")||(n==="await")||(n==="import")||(n==="export")||(n==="enum")||(n==="do")||(n==="with")||(n==="finally")||(n==="null")||(n==="true")||(n==="false"));
var js_name_inner = (n) => ((()=>{let g=str_replace(str_replace(str_replace(str_replace(str_replace(str_replace(str_replace(n,"-","_"),"?","_q"),"!","_x"),">","_gt"),"<","_lt"),"*","_st"),"+","_pl");return (js_reserved_q(g)?_fl_str(g,"_"):g);})());
var js_name = (n) => (null_q(n)?"_":js_name_inner(n));
var js_esc_inner = (s) => str_replace(str_replace(str_replace(str_replace(str_replace(s,"\\","\\\\"),"\"","\\\""),"\n","\\n"),"\r","\\r"),"\t","\\t");
var js_esc = (s) => _fl_str("\"",js_esc_inner(s),"\"");
var get_block_items = (node) => (null_q(node)?list():(((get(node,"kind")==="block")&&(get(node,"type")==="Array"))?get(get(node,"fields"),"items"):node));
var cg = (n) => (null_q(n)?"null":((get(n,"kind")==="literal")?cg_literal(n):((get(n,"kind")==="variable")?js_name(get(n,"name")):((get(n,"kind")==="keyword")?js_esc(get(n,"name")):((get(n,"kind")==="template-string")?cg_template_string(n):((get(n,"kind")==="try")?cg_try(n):((get(n,"kind")==="loop")?cg_loop(n):((get(n,"kind")==="sexpr")?cg_sexpr(n):((get(n,"kind")==="block")?cg_block(n):((get(n,"kind")==="and")?cg_and(get(n,"args")):((get(n,"kind")==="or")?cg_or(get(n,"args")):((get(n,"kind")==="pattern-match")?cg_match(n):((get(n,"kind")==="await")?_fl_str("(await ",cg(get(n,"argument")),")"):((get(n,"kind")==="throw")?_fl_str("((()=>{throw new Error(String(",cg(get(n,"argument")),"))})())"):(true?"null":null)))))))))))))));
var cg_literal = (n) => ((()=>{let t=get(n,"type");let v=get(n,"value");return ((t==="number")?_fl_str(v):((t==="string")?js_esc(v):((t==="boolean")?(v?"true":"false"):((t==="symbol")?((v==="true")?"true":((v==="false")?"false":((v==="null")?"null":((v==="nil")?"null":(true?js_name(v):null))))):(true?"null":null)))));})());
var cg_template_string = (n) => _fl_str("`",str_replace(str_replace(get(n,"value"),"\\","\\\\"),"`","\\`"),"`");
var cg_try = (n) => ((()=>{let body=cg(get(n,"body"));let catch_=get(n,"catch");let finally_=get(n,"finally");let c_code=(null_q(catch_)?"":cg_catch_clause(catch_));let f_code=(null_q(finally_)?"":_fl_str("finally{",cg(finally_),"}"));return _fl_str("(()=>{try{return ",body,"}catch(err){",c_code,"}",f_code,"})()");})());
var cg_catch_clause = (c) => ((()=>{let is_sexpr=(get(c,"kind")==="sexpr");let param=(is_sexpr?js_name(get(get(get(c,"args"),0),"name")):"err");let body=(is_sexpr?cg(get(get(c,"args"),1)):cg(c));return _fl_str("let ",param,"=err;return ",body,";");})());
var cg_func_block = (n) => ((()=>{let name=js_name(get(n,"name"));let f=get(n,"fields");let params_block=get(f,"params");let body_node=get(f,"body");let ps_info=extract_params(get_block_items(params_block));let body=cg(body_node);let pre=get(ps_info,"preamble");let final_body=((_fl_length(pre)===0)?body:_fl_str("((() => { ",pre," return ",body,"; })())"));return _fl_str("function ",name,"(",get(ps_info,"params"),") { return ",final_body,"; }");})());
var cg_block = (n) => ((()=>{let t=get(n,"type");let f=get(n,"fields");return ((t==="FUNC")?cg_func_block(n):((t==="Map")?_fl_str("({",cg_map_entries(f),"})"):((t==="Array")?_fl_str("[",cg_args(get(f,"items")),"]"):(true?"null":null))));})());
var cg_map_entries = (f) => ((()=>{let items=get(f,"items");return (array_q(items)?cg_map_flat_loop(items,0,""):cg_map_loop(map_entries(f),0,""));})());
var cg_map_loop = (e,i,acc) => ((i>=_fl_length(e))?acc:((()=>{let pair=_fl_str(js_esc(get(get(e,i),0)),":",cg(get(get(e,i),1)));return cg_map_loop(e,(i+1),((i===0)?pair:_fl_str(acc,",",pair)));})()));
var cg_map_flat_loop = (it,i,acc) => ((i>=_fl_length(it))?acc:((()=>{let k=get(it,i);let v=get(it,(i+1));let key=((get(k,"kind")==="keyword")?js_esc(get(k,"name")):((get(k,"kind")==="literal")?js_esc(_fl_str(get(k,"value"))):(true?"\"_anon\"":null)));let pair=_fl_str(key,":",cg(v));return cg_map_flat_loop(it,(i+2),((i===0)?pair:_fl_str(acc,",",pair)));})()));
var cg_sexpr = (n) => ((()=>{let op=get(n,"op");return (string_q(op)?cg_sexpr_dispatch(op,get(n,"args")):_fl_str("(",cg(op),")(",cg_args(get(n,"args")),")"));})());
var cg_sexpr_dispatch = (op,args) => ((op==="if")?_fl_str("(",cg(get(args,0)),"?",cg(get(args,1)),":",((_fl_length(args)>=3)?cg(get(args,2)):"null"),")"):((op==="fn")?cg_fn(args):((op==="defn")?cg_defn(args):((op==="let")?cg_let(args):((op==="do")?_fl_str("(()=>{",cg_do_body(args,0,""),"})()"):((op==="cond")?cg_cond(args):((op==="loop")?cg_loop(args):((op==="recur")?_fl_str("{__recur:true,a:[",cg_args(args),"]}"):((op==="and")?_fl_str("(",join(map(((a) => cg(a)),args),"&&"),")"):((op==="or")?_fl_str("(",join(map(((a) => cg(a)),args),"||"),")"):((op==="+")?((_fl_length(args)===0)?"0":_fl_str("(",binop_loop(args,0,"","+"),")")):((op==="-")?((_fl_length(args)===1)?_fl_str("(-",cg(get(args,0)),")"):_fl_str("(",binop_loop(args,0,"","-"),")")):((op==="*")?((_fl_length(args)===0)?"1":_fl_str("(",binop_loop(args,0,"","*"),")")):((op==="/")?_fl_str("(",cg(get(args,0)),"/",cg(get(args,1)),")"):((op==="=")?_fl_str("(",cg(get(args,0)),"===",cg(get(args,1)),")"):((op==="<")?_fl_str("(",cg(get(args,0)),"<",cg(get(args,1)),")"):((op===">")?_fl_str("(",cg(get(args,0)),">",cg(get(args,1)),")"):((op==="<=")?_fl_str("(",cg(get(args,0)),"<=",cg(get(args,1)),")"):((op===">=")?_fl_str("(",cg(get(args,0)),">=",cg(get(args,1)),")"):((op==="!=")?_fl_str("(",cg(get(args,0)),"!==",cg(get(args,1)),")"):((op==="%")?_fl_str("(",cg(get(args,0)),"%",cg(get(args,1)),")"):((op==="while")?_fl_str("(()=>{ while(",cg(get(args,0)),") { ",cg_stmts(slice(args,1,_fl_length(args)),0,"")," } })()"):((op==="set!")?_fl_str("(",js_name(get(get(args,0),"name"))," = ",cg(get(args,1)),")"):((op==="define")?_fl_str("const ",extract_name(get(args,0)),"=",cg(get(args,1))):(true?cg_native_dispatch(op,cg_args(args)):null)))))))))))))))))))))))));
var cg_fn = (args) => ((()=>{let ps_info=extract_params(get_block_items(get(args,0)));let body=cg(get(args,1));let pre=get(ps_info,"preamble");let final_body=((_fl_length(pre)===0)?body:_fl_str("((() => { ",pre," return ",body,"; })())"));return _fl_str("((",get(ps_info,"params"),") => ",final_body,")");})());
var cg_defn = (args) => ((()=>{let ps_info=extract_params(get_block_items(get(args,1)));let body=cg(get(args,2));let pre=get(ps_info,"preamble");let final_body=((_fl_length(pre)===0)?body:_fl_str("((() => { ",pre," return ",body,"; })())"));return _fl_str("var ",extract_name(get(args,0))," = (",get(ps_info,"params"),") => ",final_body);})());
var cg_let = (args) => ((()=>{let items=get_block_items(get(args,0));let first=get(items,0);let nested=((get(first,"kind")==="block")&&(get(first,"type")==="Array"));let bindings=(nested?cg_let_2d(items,0,""):cg_let_1d(items,0,""));let body=cg_do_body(slice(args,1,_fl_length(args)),0,"");return _fl_str("((()=>{",bindings,body,"})())");})());
var cg_let_1d = (it,i,acc) => ((i>=_fl_length(it))?acc:cg_let_1d(it,(i+2),_fl_str(acc,"let ",extract_name(get(it,i)),"=",cg(get(it,(i+1))),";")));
var cg_let_2d = (it,i,acc) => ((i>=_fl_length(it))?acc:((()=>{let p=get_block_items(get(it,i));return cg_let_2d(it,(i+1),_fl_str(acc,"let ",extract_name(get(p,0)),"=",cg(get(p,1)),";"));})()));
var cg_do_body = (args,i,acc) => ((i>=_fl_length(args))?acc:((()=>{let last=(i===(_fl_length(args)-1));let c=cg(get(args,i));let sep=(last?"return ":"");return cg_do_body(args,(i+1),_fl_str(acc,sep,c,";"));})()));
var cg_stmts = (args,i,acc) => ((i>=_fl_length(args))?acc:cg_stmts(args,(i+1),_fl_str(acc,cg(get(args,i)),";")));
var cg_cond = (args) => ((_fl_length(args)===0)?"null":((()=>{let first=get(args,0);let nested=((get(first,"kind")==="block")&&(get(first,"type")==="Array"));return (nested?cg_cond_nested(args,(_fl_length(args)-1),"null"):cg_cond_flat(args,0,"null"));})()));
var cg_cond_nested = (args,i,acc) => ((i<0)?acc:((()=>{let items=get_block_items(get(args,i));return cg_cond_nested(args,(i-1),_fl_str("(",cg(get(items,0)),"?",cg(get(items,1)),":",acc,")"));})()));
var cg_cond_flat = (args,i,acc) => ((()=>{let len=_fl_length(args);return ((i>=len)?acc:((i===(len-1))?_fl_str("(",cg(get(args,i)),")"):_fl_str("(",cg(get(args,i)),"?",cg(get(args,(i+1))),":",cg_cond_flat(args,(i+2),acc),")")));})());
var cg_loop = (args) => ((()=>{let items=get_block_items(get(args,0));let first=get(items,0);let nested=((get(first,"kind")==="block")&&(get(first,"type")==="Array"));let inits=(nested?loop_inits_2d(items,0,""):loop_inits_1d(items,0,""));let names=(nested?loop_names_2d(items,0,""):loop_names_1d(items,0,""));let body=cg_do_body(slice(args,1,_fl_length(args)),0,"");return _fl_str("((()=>{",inits,"while(true){let __r=(()=>{",body,"})();if(__r&&__r.__recur){",((_fl_length(names)===0)?"":_fl_str("[",names,"]=__r.a;")),"continue;}return __r;}})())");})());
var loop_inits_1d = (it,i,acc) => ((i>=_fl_length(it))?acc:loop_inits_1d(it,(i+2),_fl_str(acc,"let ",extract_name(get(it,i)),"=",cg(get(it,(i+1))),";")));
var loop_inits_2d = (it,i,acc) => ((i>=_fl_length(it))?acc:((()=>{let p=get_block_items(get(it,i));return loop_inits_2d(it,(i+1),_fl_str(acc,"let ",extract_name(get(p,0)),"=",cg(get(p,1)),";"));})()));
var loop_names_1d = (it,i,acc) => ((i>=_fl_length(it))?acc:((()=>{let n=extract_name(get(it,i));return loop_names_1d(it,(i+2),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));
var loop_names_2d = (it,i,acc) => ((i>=_fl_length(it))?acc:((()=>{let p=get_block_items(get(it,i));let n=extract_name(get(p,0));return loop_names_2d(it,(i+1),((_fl_length(acc)===0)?n:_fl_str(acc,",",n)));})()));
var cg_args = (args) => args_loop(args,0,"");
var args_loop = (args,i,acc) => ((null_q(args)||(i>=_fl_length(args)))?acc:((()=>{let c=cg(get(args,i));return args_loop(args,(i+1),((i===0)?c:_fl_str(acc,",",c)));})()));
var binop_loop = (args,i,acc,op) => ((i>=_fl_length(args))?acc:((()=>{let c=cg(get(args,i));return binop_loop(args,(i+1),((i===0)?c:_fl_str(acc,op,c)),op);})()));
var extract_name = (n) => ((get(n,"kind")==="variable")?js_name(get(n,"name")):((get(n,"kind")==="literal")?js_name(get(n,"value")):(true?"_anon":null)));
var extract_params = (it) => extract_params_loop(it,0,"","",0);
var extract_params_loop = (it,i,ps,pre,tc) => ((null_q(it)||(i>=_fl_length(it)))?({"params":ps,"preamble":pre}):((()=>{let c=get(it,i);let k=get(c,"kind");return (((k==="variable")||(k==="literal"))?extract_params_loop(it,(i+1),((_fl_length(ps)===0)?extract_name(c):_fl_str(ps,",",extract_name(c))),pre,tc):(((k==="block")&&(get(c,"type")==="Array"))?((()=>{let t=_fl_str("_arg",tc);let sub=get(get(c,"fields"),"items");return extract_params_loop(it,(i+1),((_fl_length(ps)===0)?t:_fl_str(ps,",",t)),_fl_str(pre,destructure_loop(sub,t,0)),(tc+1));})()):extract_params_loop(it,(i+1),((_fl_length(ps)===0)?"p":_fl_str(ps,",p")),pre,tc)));})()));
var destructure_loop = (it,t,i) => ((i>=_fl_length(it))?"":_fl_str("let ",extract_name(get(it,i)),"=",t,"[",i,"]; ",destructure_loop(it,t,(i+1))));
var cg_native_dispatch = (op,as) => ((op==="str")?_fl_str("_fl_str(",as,")"):((op==="length")?_fl_str("_fl_length(",as,")"):((op==="println")?_fl_str("_fl_print(",as,")"):((op==="print")?_fl_str("_fl_print(",as,")"):(true?_fl_str(js_name(op),"(",as,")"):null)))));
var prelude_parts = () => list("const _fl_str = (...xs) => xs.map(x => x==null?'':String(x)).join('');","const _fl_length = (x) => (x?x.length:0);","const _fl_get = (o,k,d) => { if(o==null)return d||null; let ks=String(k).startsWith(':')?k.slice(1):String(k); if(Array.isArray(o)){let idx=parseInt(ks);if(!isNaN(idx))return o[idx]!==undefined?o[idx]:(d||null);if(ks==='length')return o.length;} if(typeof o==='object'){if(o[ks]!==undefined)return o[ks];} return d||null; }","const _fl_null_q = (v) => v===null||v===undefined;","const _fl_keys = (o) => o?Object.keys(o):[];","const _fl_map_set = (o,k,v) => ({...o,[k]:v});","const _fl_has_key_q = (o,k) => o?(String(k) in o):false;","const _fl_append = (l,x) => [...(l||[]),x];","const list = (...args) => [...args];","const append = (l,x) => [...(l||[]),x];","const _fl_first = (l) => (l&&l.length>0)?l[0]:null;","const _fl_last = (l) => (l&&l.length>0)?l[l.length-1]:null;","const _fl_rest = (l) => (l&&l.length>0)?l.slice(1):[];","const _fl_slice = (l,a,b) => (l||[]).slice(a,b);","const _fl_map = (arr,fn) => (arr||[]).map(x=>fn(x));","const _fl_filter = (arr,fn) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});","const _fl_reduce = (arr,fn,init) => (arr||[]).reduce((a,x)=>fn(a,x),init);","const _fl_some = (f,l) => (l||[]).some(x=>f(x));","const _fl_every = (f,l) => (l||[]).every(x=>f(x));","const _fl_file_read = (p) => require('fs').readFileSync(p,'utf8');","const _fl_file_write = (p,c) => require('fs').writeFileSync(p,c);","const _fl_file_exists = (p) => require('fs').existsSync(p);","const _fl_file_delete = (p) => { try { require('fs').unlinkSync(p); } catch(e) {} };","const _fl_file_append = (p,c) => require('fs').appendFileSync(p,String(c));","const _fl_file_copy = (s,d) => require('fs').copyFileSync(s,d);","const _fl_file_rename = (o,n) => require('fs').renameSync(o,n);","const _fl_file_size = (p) => { try { return require('fs').statSync(p).size; } catch(e) { return 0; } };","const _fl_file_modified = (p) => { try { return require('fs').statSync(p).mtimeMs; } catch(e) { return 0; } };","const _fl_file_mkdir = (p) => { try { require('fs').mkdirSync(p,{recursive:true}); } catch(e) {} };","const _fl_file_rmdir = (p) => { try { require('fs').rmSync(p,{recursive:true,force:true}); } catch(e) {} };","const _fl_file_list = (p) => { try { return require('fs').readdirSync(p); } catch(e) { return []; } };","const _fl_process_run = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };","const _fl_process_run_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };","const _fl_process_exec = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };","const _fl_process_exec_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };","const _fl_process_spawn = (cmd,args) => { try { const r=require('child_process').spawnSync(cmd,args||[],{encoding:'utf8'}); return r.stdout||''; } catch(e) { return ''; } };","const _fl_process_kill = (pid) => { try { process.kill(pid); } catch(e) {} };","const _fl_process_wait = (pid) => null;","const _fl_env_get = (k) => process.env[k]||null;","const _fl_env_set = (k,v) => { process.env[k]=String(v); };","const _fl_env_all = () => process.env;","const _fl_file_is_file = (p) => { try { return require('fs').statSync(p).isFile(); } catch(e) { return false; } };","const _fl_file_is_dir = (p) => { try { return require('fs').statSync(p).isDirectory(); } catch(e) { return false; } };","const _fl_process_exists = (pid) => { try { process.kill(pid,0); return true; } catch(e) { return false; } };","const _fl_process_getcwd = () => process.cwd();","const _fl_process_chdir = (p) => { try { process.chdir(p); } catch(e) {} };","const _fl_process_pid = () => process.pid;","const _fl_process_ppid = () => process.ppid||null;","const file_read = (p) => _fl_file_read(String(p));","const file_write = (p,c) => _fl_file_write(String(p),String(c));","const file_exists = (p) => _fl_file_exists(String(p));","const _fl_get_argv = () => (typeof process!=='undefined'?process.argv.slice(2):[]);","const _fl_print = (v) => { console.log(v); return v; }","const null_q = _fl_null_q;","const some_q = _fl_some;","const every_q = _fl_every;","const cli_args = _fl_get_argv;","const get = _fl_get;","const keys = _fl_keys;","const has_key_q = _fl_has_key_q;","const slice = _fl_slice;","const first = _fl_first;","const last = _fl_last;","const rest = _fl_rest;","const map = (fn,arr) => (arr||[]).map(x=>fn(x));","const filter = (fn,arr) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});","const reduce = (fn,init,arr) => (arr||[]).reduce((a,x)=>fn(a,x),init);","const print = _fl_print;","const println = (v) => { console.log(v==null?'':String(v)); return v; }","const str_replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); return st.split(String(ov)).join(nv==null?'':String(nv)); };","const str_index_of = (s,sub) => (typeof s==='string'&&typeof sub==='string')?s.indexOf(sub):-1;","const index_of = str_index_of;","const str_slice = (s,a,b) => s?(b===undefined?s.slice(a):s.slice(a,b)):'';","const substring = str_slice;","const char_at = (s,i) => (s&&s[i])||null;","const char_code_at = (s,i) => typeof s==='string'?s.charCodeAt(i):0;","const trim = (s) => String(s||'').trim();","const starts_with_q = (s,p) => String(s||'').startsWith(String(p||''));","const ends_with_q = (s,sf) => String(s||'').endsWith(String(sf||''));","const replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); if(ov instanceof RegExp)return st.replace(ov,nv==null?'':String(nv)); return st.split(String(ov)).join(nv==null?'':String(nv)); };","const split = (s,sep) => String(s||'').split(sep);","const str_join = (arr,sep) => (arr||[]).join(sep===undefined?'':sep);","const join = str_join;","const concat = (a,b) => (Array.isArray(a)&&Array.isArray(b))?[...a,...b]:String(a||'')+String(b||'');","const push = (arr,v) => [...(arr||[]),v];","const pop = (arr) => (arr&&arr.length>0)?arr.slice(0,-1):[];","const reverse = (arr) => Array.isArray(arr)?[...arr].reverse():arr;","const sort_by = (arr,fn) => Array.isArray(arr)?[...arr].sort((a,b)=>fn(a)<fn(b)?-1:fn(a)>fn(b)?1:0):arr;","const flat_map = (arr,fn) => (arr||[]).flatMap(fn);","const range = (s,e) => { const r=[]; let st=e===undefined?0:s; let en=e===undefined?s:e; for(let i=st;i<en;i++)r.push(i); return r; };","const merge = (a,b) => Object.assign({},a,b);","const assoc = (o,k,v) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); r[key]=v; return r; };","const dissoc = (o,k) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); delete r[key]; return r; };","var map_entries = (m) => m instanceof Map?[...m.entries()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.entries(m):[]);","var map_keys = (m) => m instanceof Map?[...m.keys()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.keys(m):[]);","var map_values = (m) => m instanceof Map?[...m.values()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.values(m):[]);","const array_q = (v) => Array.isArray(v);","var list_q = (v) => Array.isArray(v);","var map_q = (v) => v!==null&&typeof v==='object'&&!Array.isArray(v);","var fn_q = (v) => typeof v==='function';","const number_q = (v) => typeof v==='number';","const string_q = (v) => typeof v==='string';","var str_upper = (s) => String(s||'').toUpperCase();","var str_lower = (s) => String(s||'').toLowerCase();","var str_contains = (s,sub) => String(s||'').includes(String(sub||''));","var str_starts_with = (s,p) => String(s||'').startsWith(String(p||''));","var str_ends_with = (s,sf) => String(s||'').endsWith(String(sf||''));","var str_trim = (s) => String(s||'').trim();","var str_length = (s) => String(s||'').length;","var str_split = (s,sep) => String(s||'').split(sep);","var take = (n,arr) => (arr||[]).slice(0,n);","var drop = (n,arr) => (arr||[]).slice(n);","var zip = (a,b) => { const r=[]; const l=Math.min((a||[]).length,(b||[]).length); for(let i=0;i<l;i++)r.push([a[i],b[i]]); return r; };","var flatten = (arr) => (arr||[]).flat();","var sort = (arr,fn) => fn?[...(arr||[])].sort((a,b)=>fn(a,b)?-1:1):[...(arr||[])].sort();","var math_sqrt = (n) => Math.sqrt(n);","var math_pi = Math.PI;","var unknown = (...a) => a[a.length-1];","function _fl_type_of(v) { if(v===null||v===undefined)return 'nil'; if(Array.isArray(v))return 'list'; return typeof v; }","const not = (v) => !v;","const abs = (n) => Math.abs(n);","const floor = (n) => Math.floor(n);","const ceil_val = (n) => Math.ceil(n);","const round = (n) => Math.round(n);","const max_val = (a,b) => a>b?a:b;","const min_val = (a,b) => a<b?a:b;","const error = (msg) => { throw new Error(String(msg)); };","const now_ms = () => Date.now();","const now_iso = () => new Date().toISOString();","const now_unix = () => Math.floor(Date.now()/1000);","const json_parse = (s) => { try{return JSON.parse(s);}catch(e){return null;} };","const json_stringify = (v) => JSON.stringify(v);","const shell_exec = (cmd,inp) => { try{const {execSync}=require('child_process');const opts={encoding:'utf8'};if(inp)opts.input=inp;return execSync(cmd,opts);}catch(e){return '';} };","const _fl_run_inherit = (cmd) => { require('child_process').spawnSync(cmd,{shell:true,stdio:'inherit'}); };","const __fl_routes = [];","const _fl_server_get = (path,fn) => { __fl_routes.push({method:'GET',path,fn}); };","const _fl_server_start = (port) => { const http=require('http'); http.createServer(async(req,res)=>{ const r=__fl_routes.find(r=>r.method===req.method&&r.path===require('url').parse(req.url).pathname); if(r){const result=await(typeof r.fn==='string'?eval(r.fn):r.fn)(req);res.end(String(result));}else{res.statusCode=404;res.end('Not Found');} }).listen(port);console.log('Server on '+port); };","const server_get = _fl_server_get;","const server_start = _fl_server_start;");
var runtime_prelude = () => join(prelude_parts(),"\n");
var fl__gtjs_code = (ast) => reduce(((acc,n) => _fl_str(acc,cg(n),";\n")),"",ast);
var fl__gtjs_with_prelude = (ast) => _fl_str(runtime_prelude(),"\n",fl__gtjs_code(ast));
var count_parens = (tokens) => reduce(((acc,tok) => ((()=>{let k=(get(tok,"type")||get(tok,"kind"));return ((k==="LParen")?(acc+1):((k==="RParen")?(acc-1):acc));})())),0,tokens);
var compile_file = (input,output) => ((()=>{let src=file_read(input);let tokens=lex(src);let depth=count_parens(tokens);let ast=parse(tokens);let node_count=_fl_length(ast);let js=fl__gtjs_with_prelude(ast);return (()=>{(not((depth===0))?_fl_print(_fl_str("Warning: ",input,": 괄호 불균형 (깊이=",depth,")")):null);file_write(output,js);_fl_print(_fl_str("Parsed: ",node_count," nodes"));return _fl_print(_fl_str("Compiled ",input," -> ",output));})();})());
var str_lines = (s) => split(s,"\n");
var str_words = (s) => split(trim(s)," ");
var str_join_lines = (lines) => str_join_loop(lines,0,"");
var str_join_loop = (lst,i,acc) => ((i>=_fl_length(lst))?acc:str_join_loop(lst,(i+1),((i===0)?get(lst,0):_fl_str(acc,"\n",get(lst,i)))));
var str_count = (s,sub) => ((_fl_length(sub)===0)?0:str_count_loop(s,sub,0,0));
var str_count_loop = (s,sub,pos,acc) => ((()=>{let rest=substring(s,pos,_fl_length(s));let idx=index_of(rest,sub);return ((idx<0)?acc:str_count_loop(s,sub,(pos+idx+_fl_length(sub)),(acc+1)));})());
var csv_parse_line = (line) => split(line,",");
var csv_parse = (csv) => ((()=>{let lines=split(csv,"\n");return csv_parse_loop(lines,0,list());})());
var csv_parse_loop = (lines,i,acc) => ((i>=_fl_length(lines))?acc:csv_parse_loop(lines,(i+1),append(acc,csv_parse_line(get(lines,i)))));
var data_json_parse = (s) => json_parse(s);
var data_json_str = (obj) => json_stringify(obj);
var data_json_pretty = (obj) => json_stringify(obj);
var to_query_string = (obj) => to_query_loop(keys(obj),obj,0,list());
var to_query_loop = (ks,obj,i,acc) => ((i>=_fl_length(ks))?join(acc,"&"):((()=>{let k=get(ks,i);let v=get(obj,k);return to_query_loop(ks,obj,(i+1),append(acc,_fl_str(k,"=",v)));})()));
var hash_simple = (s) => hash_simple_loop(_fl_str(s),0,5381,0);
var hash_simple_loop = (s,i,hash,max) => ((i>=_fl_length(s))?(abs(hash)%2147483647):hash_simple_loop(s,(i+1),((hash*33)+char_code_at(s,i)),(i+1)));
var hash_fnv1a = (s) => ((()=>{let fnv_offset=2166136261;let fnv_prime=16777619;return hash_fnv_loop(_fl_str(s),0,fnv_offset);})());
var hash_fnv_loop = (s,i,hash) => ((i>=_fl_length(s))?(abs(hash)%2147483647):hash_fnv_loop(s,(i+1),(bit_xor(hash,char_code_at(s,i))*16777619)));
var hash_djb2 = (s) => hash_djb_loop(_fl_str(s),0,5381);
var hash_djb_loop = (s,i,hash) => ((i>=_fl_length(s))?(abs(hash)%2147483647):hash_djb_loop(s,(i+1),((hash*33)+char_code_at(s,i))));
var hash_object = (obj) => hash_simple(json_stringify(obj));
var hash_consistent = (s,seed) => ((()=>{let h=hash_simple(s);return (((h*seed)+seed)%2147483647);})());
var now_s = () => floor((now()/1000));
var time_diff_ms = (t1,t2) => (t2-t1);
var time_elapsed = (start) => (now()-start);
var date_parts = (ts) => ({"ts":ts,"s":floor((ts/1000)),"m":floor((ts/60000)),"h":floor((ts/3600000)),"d":floor((ts/86400000))});
var ts_to_s = (ts) => floor((ts/1000));
var s_to_ts = (s) => (s*1000);
var time_ago = (ts) => ((()=>{let diff=(now()-ts);let s=floor((diff/1000));let m=floor((s/60));let h=floor((m/60));let d=floor((h/24));return ((s<60)?_fl_str(s,"s ago"):((m<60)?_fl_str(m,"m ago"):((h<24)?_fl_str(h,"h ago"):(true?_fl_str(d,"d ago"):null))));})());
var file_append = (path,content) => _fl_file_append(_fl_str(path),_fl_str(content));
var file_exists_q = (path) => file_exists(_fl_str(path));
var file_delete = (path) => _fl_file_delete(_fl_str(path));
var file_copy = (src,dest) => _fl_file_copy(_fl_str(src),_fl_str(dest));
var file_rename = (old,new_) => _fl_file_rename(_fl_str(old),_fl_str(new_));
var file_size = (path) => _fl_file_size(_fl_str(path));
var file_modified = (path) => _fl_file_modified(_fl_str(path));
var file_json = (path) => json_parse(file_read(_fl_str(path)));
var file_json_write = (path,obj) => file_write(_fl_str(path),json_stringify(obj));
var file_lines = (path) => str_lines(file_read(_fl_str(path)));
var file_mkdir = (path) => _fl_file_mkdir(_fl_str(path));
var file_rmdir = (path) => _fl_file_rmdir(_fl_str(path));
var file_list = (path) => _fl_file_list(_fl_str(path));
var file_is_file_q = (path) => _fl_file_is_file(_fl_str(path));
var file_is_dir_q = (path) => _fl_file_is_dir(_fl_str(path));
var process_run = (cmd) => _fl_process_run(_fl_str(cmd));
var process_run_args = (cmd,args) => _fl_process_run_args(_fl_str(cmd),args);
var process_exec = (cmd) => _fl_process_exec(_fl_str(cmd));
var process_exec_args = (cmd,args) => _fl_process_exec_args(_fl_str(cmd),args);
var process_spawn = (cmd,args) => _fl_process_spawn(_fl_str(cmd),args);
var process_kill = (pid) => _fl_process_kill(floor(pid));
var process_exists_q = (pid) => _fl_process_exists(floor(pid));
var process_wait = (pid) => _fl_process_wait(floor(pid));
var shell_run = (cmd) => _fl_run_inherit(_fl_str(cmd));
var shell_pipe = (cmd1,cmd2) => process_exec(_fl_str(cmd1," | ",cmd2));
var env_get = (key) => _fl_env_get(_fl_str(key));
var env_set = (key,value) => _fl_env_set(_fl_str(key),_fl_str(value));
var env_all = () => _fl_env_all();
var getcwd = () => _fl_process_getcwd();
var chdir = (path) => _fl_process_chdir(_fl_str(path));
var pid = () => _fl_process_pid();
var pid_parent = () => _fl_process_ppid();
var vector_add = (v1,v2) => map(((i) => (get(v1,i)+get(v2,i))),range(0,_fl_length(v1)));
var vector_dot = (v1,v2) => reduce(((acc,i) => (acc+(get(v1,i)*get(v2,i)))),0,range(0,_fl_length(v1)));
var vector_magnitude = (v) => math_sqrt(reduce(((acc,x) => (acc+(x*x))),0,v));
var cosine_sim = (v1,v2) => ((()=>{let dot=vector_dot(v1,v2);let mag1=vector_magnitude(v1);let mag2=vector_magnitude(v2);return (((mag1===0)||(mag2===0))?0:(dot/(mag1*mag2)));})());
var do_run = (input,extra_args) => ((()=>{let output=_fl_str("/tmp/fl-run-",now_ms(),".js");let args_str=str_join(extra_args," ");return (()=>{compile_file(input,output);shell_run(_fl_str("node ",output," ",args_str));return file_delete(output);})();})());
var cli_main = () => ((()=>{let argv=cli_args();return (null_q(argv)?null:((_fl_length(argv)===0)?null:((()=>{let cmd=get(argv,0);return ((cmd==="run")?((()=>{let input=get(argv,1);let extra=slice(argv,2,_fl_length(argv));return do_run(input,extra);})()):((()=>{let input=get(argv,0);let output=((_fl_length(argv)>=2)?get(argv,1):_fl_str(input,".out.js"));return compile_file(input,output);})()));})())));})());
cli_main();
