const _fl_str = (...xs) => xs.map(x => x==null?'':String(x)).join('');
const _fl_length = (x) => (x?x.length:0);
const _fl_get = (o,k,d) => { if(o==null)return d||null; let ks=String(k).startsWith(':')?k.slice(1):String(k); if(Array.isArray(o)){let idx=parseInt(ks);if(!isNaN(idx))return o[idx]!==undefined?o[idx]:(d||null);if(ks==='length')return o.length;} if(typeof o==='object'){if(o[ks]!==undefined)return o[ks];} return d||null; }
const _fl_null_q = (v) => v===null||v===undefined;
const _fl_keys = (o) => o?Object.keys(o):[];
const _fl_map_set = (o,k,v) => ({...o,[k]:v});
const _fl_has_key_q = (o,k) => o?(String(k) in o):false;
const _fl_append = (l,x) => [...(l||[]),x];
const list = (...args) => [...args];
const append = (l,x) => [...(l||[]),x];
const _fl_first = (l) => (l&&l.length>0)?l[0]:null;
const _fl_last = (l) => (l&&l.length>0)?l[l.length-1]:null;
const _fl_rest = (l) => (l&&l.length>0)?l.slice(1):[];
const _fl_slice = (l,a,b) => (l||[]).slice(a,b);
const _fl_map = (arr,fn) => (arr||[]).map(x=>fn(x));
const _fl_filter = (arr,fn) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const _fl_reduce = (arr,fn,init) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const _fl_some = (f,l) => (l||[]).some(x=>f(x));
const _fl_every = (f,l) => (l||[]).every(x=>f(x));
const _fl_file_read = (p) => require('fs').readFileSync(p,'utf8');
const _fl_file_write = (p,c) => require('fs').writeFileSync(p,c);
const _fl_file_exists = (p) => require('fs').existsSync(p);
const _fl_file_delete = (p) => { try { require('fs').unlinkSync(p); } catch(e) {} };
const _fl_file_append = (p,c) => require('fs').appendFileSync(p,String(c));
const _fl_file_copy = (s,d) => require('fs').copyFileSync(s,d);
const _fl_file_rename = (o,n) => require('fs').renameSync(o,n);
const _fl_file_size = (p) => { try { return require('fs').statSync(p).size; } catch(e) { return 0; } };
const _fl_file_modified = (p) => { try { return require('fs').statSync(p).mtimeMs; } catch(e) { return 0; } };
const _fl_file_mkdir = (p) => { try { require('fs').mkdirSync(p,{recursive:true}); } catch(e) {} };
const _fl_file_rmdir = (p) => { try { require('fs').rmSync(p,{recursive:true,force:true}); } catch(e) {} };
const _fl_file_list = (p) => { try { return require('fs').readdirSync(p); } catch(e) { return []; } };
const _fl_process_run = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_run_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec = (cmd) => { try { return require('child_process').execSync(cmd,{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_exec_args = (cmd,args) => { try { return require('child_process').execSync(cmd+' '+(args||[]).join(' '),{encoding:'utf8'}); } catch(e) { return ''; } };
const _fl_process_spawn = (cmd,args) => { try { const r=require('child_process').spawnSync(cmd,args||[],{encoding:'utf8'}); return r.stdout||''; } catch(e) { return ''; } };
const _fl_process_kill = (pid) => { try { process.kill(pid); } catch(e) {} };
const _fl_process_wait = (pid) => null;
const _fl_env_get = (k) => process.env[k]||null;
const _fl_env_set = (k,v) => { process.env[k]=String(v); };
const _fl_env_all = () => process.env;
const _fl_file_is_file = (p) => { try { return require('fs').statSync(p).isFile(); } catch(e) { return false; } };
const _fl_file_is_dir = (p) => { try { return require('fs').statSync(p).isDirectory(); } catch(e) { return false; } };
const _fl_process_exists = (pid) => { try { process.kill(pid,0); return true; } catch(e) { return false; } };
const _fl_process_getcwd = () => process.cwd();
const _fl_process_chdir = (p) => { try { process.chdir(p); } catch(e) {} };
const _fl_process_pid = () => process.pid;
const _fl_process_ppid = () => process.ppid||null;
var file_read = (p) => _fl_file_read(String(p));
var file_write = (p,c) => _fl_file_write(String(p),String(c));
var file_exists = (p) => _fl_file_exists(String(p));
const _fl_get_argv = () => (typeof process!=='undefined'?process.argv.slice(2):[]);
const _fl_print = (v) => { console.log(v); return v; }
const null_q = _fl_null_q;
const some_q = _fl_some;
const every_q = _fl_every;
const cli_args = _fl_get_argv;
const get = _fl_get;
const keys = _fl_keys;
const has_key_q = _fl_has_key_q;
const slice = _fl_slice;
const first = _fl_first;
const last = _fl_last;
const rest = _fl_rest;
const map = (fn,arr) => (arr||[]).map(x=>fn(x));
const filter = (fn,arr) => (arr||[]).filter(x=>{const r=fn(x);return r!==false&&r!==null;});
const reduce = (fn,init,arr) => (arr||[]).reduce((a,x)=>fn(a,x),init);
const print = _fl_print;
const println = (v) => { console.log(v==null?'':String(v)); return v; }
var str_replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const str_index_of = (s,sub) => (typeof s==='string'&&typeof sub==='string')?s.indexOf(sub):-1;
const index_of = str_index_of;
const str_slice = (s,a,b) => s?(b===undefined?s.slice(a):s.slice(a,b)):'';
const substring = str_slice;
const char_at = (s,i) => (s&&s[i])||null;
const char_code_at = (s,i) => typeof s==='string'?s.charCodeAt(i):0;
const trim = (s) => String(s||'').trim();
const starts_with_q = (s,p) => String(s||'').startsWith(String(p||''));
const ends_with_q = (s,sf) => String(s||'').endsWith(String(sf||''));
const replace = (s,ov,nv) => { if(s==null)return ''; const st=String(s); if(ov instanceof RegExp)return st.replace(ov,nv==null?'':String(nv)); return st.split(String(ov)).join(nv==null?'':String(nv)); };
const split = (s,sep) => String(s||'').split(sep);
const str_join = (arr,sep) => (arr||[]).join(sep===undefined?'':sep);
const join = str_join;
const concat = (a,b) => (Array.isArray(a)&&Array.isArray(b))?[...a,...b]:String(a||'')+String(b||'');
const push = (arr,v) => [...(arr||[]),v];
const pop = (arr) => (arr&&arr.length>0)?arr.slice(0,-1):[];
const reverse = (arr) => Array.isArray(arr)?[...arr].reverse():arr;
const sort_by = (arr,fn) => Array.isArray(arr)?[...arr].sort((a,b)=>fn(a)<fn(b)?-1:fn(a)>fn(b)?1:0):arr;
const flat_map = (arr,fn) => (arr||[]).flatMap(fn);
const range = (s,e) => { const r=[]; let st=e===undefined?0:s; let en=e===undefined?s:e; for(let i=st;i<en;i++)r.push(i); return r; };
const merge = (a,b) => Object.assign({},a,b);
const assoc = (o,k,v) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); r[key]=v; return r; };
const dissoc = (o,k) => { const r=Object.assign({},o); const key=typeof k==='string'&&k.startsWith(':')?k.slice(1):String(k); delete r[key]; return r; };
var map_entries = (m) => m instanceof Map?[...m.entries()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.entries(m):[]);
var map_keys = (m) => m instanceof Map?[...m.keys()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.keys(m):[]);
var map_values = (m) => m instanceof Map?[...m.values()]:(m&&typeof m==='object'&&!Array.isArray(m)?Object.values(m):[]);
const array_q = (v) => Array.isArray(v);
var list_q = (v) => Array.isArray(v);
var map_q = (v) => v!==null&&typeof v==='object'&&!Array.isArray(v);
var fn_q = (v) => typeof v==='function';
const number_q = (v) => typeof v==='number';
const string_q = (v) => typeof v==='string';
var str_upper = (s) => String(s||'').toUpperCase();
var str_lower = (s) => String(s||'').toLowerCase();
var str_contains = (s,sub) => String(s||'').includes(String(sub||''));
var str_starts_with = (s,p) => String(s||'').startsWith(String(p||''));
var str_ends_with = (s,sf) => String(s||'').endsWith(String(sf||''));
var str_trim = (s) => String(s||'').trim();
var str_length = (s) => String(s||'').length;
var str_split = (s,sep) => String(s||'').split(sep);
var take = (n,arr) => (arr||[]).slice(0,n);
var drop = (n,arr) => (arr||[]).slice(n);
var zip = (a,b) => { const r=[]; const l=Math.min((a||[]).length,(b||[]).length); for(let i=0;i<l;i++)r.push([a[i],b[i]]); return r; };
var flatten = (arr) => (arr||[]).flat();
var sort = (arr,fn) => fn?[...(arr||[])].sort((a,b)=>fn(a,b)?-1:1):[...(arr||[])].sort();
var math_sqrt = (n) => Math.sqrt(n);
var math_pi = Math.PI;
var unknown = (...a) => a[a.length-1];
function _fl_type_of(v) { if(v===null||v===undefined)return 'nil'; if(Array.isArray(v))return 'list'; return typeof v; }
const not = (v) => !v;
const abs = (n) => Math.abs(n);
const floor = (n) => Math.floor(n);
const ceil_val = (n) => Math.ceil(n);
const round = (n) => Math.round(n);
const max_val = (a,b) => a>b?a:b;
const min_val = (a,b) => a<b?a:b;
const error = (msg) => { throw new Error(String(msg)); };
const now_ms = () => Date.now();
const now_iso = () => new Date().toISOString();
const now_unix = () => Math.floor(Date.now()/1000);
const json_parse = (s) => { try{return JSON.parse(s);}catch(e){return null;} };
const json_stringify = (v) => JSON.stringify(v);
const shell_exec = (cmd,inp) => { try{const {execSync}=require('child_process');const opts={encoding:'utf8'};if(inp)opts.input=inp;return execSync(cmd,opts);}catch(e){return '';} };
const _fl_run_inherit = (cmd) => { require('child_process').spawnSync(cmd,{shell:true,stdio:'inherit'}); };
const __fl_routes = [];
const _fl_server_get = (path,fn) => { __fl_routes.push({method:'GET',path,fn}); };
const _fl_server_start = (port) => { const http=require('http'); http.createServer(async(req,res)=>{ const r=__fl_routes.find(r=>r.method===req.method&&r.path===require('url').parse(req.url).pathname); if(r){const result=await(typeof r.fn==='string'?eval(r.fn):r.fn)(req);res.end(String(result));}else{res.statusCode=404;res.end('Not Found');} }).listen(port);console.log('Server on '+port); };
const server_get = _fl_server_get;
const server_start = _fl_server_start;
const _fl_runLoopReg = new Map(); let _fl_rlNextId = 9000; const _fl_initQ = () => { if(!globalThis.__flEventQueue) globalThis.__flEventQueue=[]; if(!globalThis.__flErrorQueue) globalThis.__flErrorQueue=[]; };
var fl_event_tick = () => { _fl_initQ(); const q=globalThis.__flEventQueue; if(q.length===0) return 0; const ev=q.shift(); try { const r=typeof ev.handler==='function'?ev.handler(...(ev.args||[])):null; const o=r!=null?String(r):''; if(o&&ev.sock&&!ev.sock.destroyed) try{ev.sock.write(o.endsWith('\n')?o:o+'\n');}catch(we){globalThis.__flErrorQueue.push(['io-err','recoverable','write',we.message]);} } catch(e) { const fatal=e.message?.includes('Maximum call stack')||e.message?.includes('out of memory'); globalThis.__flErrorQueue.push(['io-err',fatal?'fatal':'recoverable','handler',e.message]); if(ev.sock&&!ev.sock.destroyed) try{ev.sock.write('ERR '+e.message+'\n');}catch{} } return 1; };
var fl_event_drain = () => { _fl_initQ(); let cnt=0; while(globalThis.__flEventQueue.length>0){fl_event_tick();cnt++;} return cnt; };
var fl_event_queue_size = () => (globalThis.__flEventQueue||[]).length;
var fl_run_loop = (ms) => { if(typeof ms!=='number'||ms<1) throw new Error('fl-run-loop: ms must be positive, got '+ms); const id=_fl_rlNextId++; _fl_runLoopReg.set(id,setInterval(()=>{_fl_initQ();while(globalThis.__flEventQueue.length>0)fl_event_tick();},ms)); return id; };
var fl_run_loop_stop = (id) => { const t=_fl_runLoopReg.get(id); if(t===undefined) return false; clearInterval(t); _fl_runLoopReg.delete(id); return true; };
function is_digit_q(c) { return (null_q(c)?false:((c>="0")&&(c<="9"))); };
function is_alpha_q(c) { return (null_q(c)?false:(((c>="a")&&(c<="z"))||((c>="A")&&(c<="Z")))); };
function is_alnum_q(c) { return (is_digit_q(c)||is_alpha_q(c)); };
function is_space_q(c) { return ((c===" ")||(c==="\t")||(c==="\n")||(c==="\r")); };
function is_symbol_char_q(c) { return (null_q(c)?false:(is_alnum_q(c)||(c==="-")||(c==="_")||(c==="?")||(c==="!")||(c==="/")||(c===".")||(c==="<")||(c===">")||(c==="=")||(c==="+")||(c==="*")||(c==="%")||(c==="&")||(c==="|")||(c==="^")||(c==="~"))); };
function make_state(src) { return ({"src":src,"idx":0,"line":1,"col":1,"tokens":[]}); };
function peek_at(st,offset) { return ((()=>{let src=get(st,"src");let i=(get(st,"idx")+offset);return ((i>=_fl_length(src))?null:char_at(src,i));})()); };
function peek(st) { return peek_at(st,0); };
function at_end_q(st) { return (get(st,"idx")>=_fl_length(get(st,"src"))); };
function advance(st) { return ((()=>{let c=peek(st);return ((c==="\n")?({"src":get(st,"src"),"idx":(get(st,"idx")+1),"line":(get(st,"line")+1),"col":1,"tokens":get(st,"tokens")}):({"src":get(st,"src"),"idx":(get(st,"idx")+1),"line":get(st,"line"),"col":(get(st,"col")+1),"tokens":get(st,"tokens")}));})()); };
function emit(st,kind,value,sl,sc) { return ({"src":get(st,"src"),"idx":get(st,"idx"),"line":get(st,"line"),"col":get(st,"col"),"tokens":append(get(st,"tokens"),({"kind":kind,"type":kind,"value":value,"line":sl,"col":sc}))}); };
function skip_comment(st) { return ((()=>{let cur=st;return (()=>{(()=>{ while((not(at_end_q(cur))&&not((peek(cur)==="\n")))) { (cur = advance(cur)); } })();return (at_end_q(cur)?cur:advance(cur));})();})()); };
function skip_ws(st) { return ((()=>{let cur=st;let running=true;return (()=>{(()=>{ while((not(at_end_q(cur))&&running)) { ((()=>{let c=peek(cur);return (is_space_q(c)?(cur = advance(cur)):((c===";")?(cur = skip_comment(cur)):(true?(running = false):null)));})()); } })();return cur;})();})()); };
function read_number_body(st,acc,has_dot,line,col) { return ((()=>{let cur=st;let res_acc=acc;let dot=has_dot;let running=true;return (()=>{(()=>{ while((not(at_end_q(cur))&&running)) { ((()=>{let c=peek(cur);return (is_digit_q(c)?(()=>{(res_acc = _fl_str(res_acc,c));return (cur = advance(cur));})():(((c===".")&&not(dot))?(()=>{(res_acc = _fl_str(res_acc,c));(dot = true);return (cur = advance(cur));})():(true?(running = false):null)));})()); } })();return emit(cur,"Number",res_acc,line,col);})();})()); };
function read_number(st) { return read_number_body(st,"",false,get(st,"line"),get(st,"col")); };
function translate_esc(c) { return ((c==="n")?"\n":((c==="t")?"\t":((c==="r")?"\r":((c==="\"")?"\"":((c==="\\")?"\\":(true?c:null)))))); };
function read_string_body(st,acc,line,col) { return ((()=>{let cur=st;let res_acc=acc;let running=true;return (()=>{(()=>{ while((not(at_end_q(cur))&&running)) { ((()=>{let c=peek(cur);return ((c==="\"")?(()=>{(cur = advance(cur));return (running = false);})():((c==="\\")?((()=>{let st2=advance(cur);let c2=peek(st2);return (()=>{(res_acc = _fl_str(res_acc,translate_esc(c2)));return (cur = advance(st2));})();})()):(true?(()=>{(res_acc = _fl_str(res_acc,c));return (cur = advance(cur));})():null)));})()); } })();return emit(cur,"String",res_acc,line,col);})();})()); };
function read_string(st) { return ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_string_body(st1,"",line,col);})()); };
function read_symbol_body_kind(st,acc,line,col,kind) { return ((()=>{let cur=st;let res_acc=acc;let running=true;return (()=>{(()=>{ while((not(at_end_q(cur))&&running)) { ((()=>{let c=peek(cur);return (is_symbol_char_q(c)?(()=>{(res_acc = _fl_str(res_acc,c));return (cur = advance(cur));})():(running = false));})()); } })();return emit(cur,kind,res_acc,line,col);})();})()); };
function read_symbol(st) { return read_symbol_body_kind(st,"",get(st,"line"),get(st,"col"),"Symbol"); };
function read_variable(st) { return ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Variable");})()); };
function read_keyword(st) { return ((()=>{let line=get(st,"line");let col=get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Keyword");})()); };
function read_token(st) { return ((()=>{let st1=skip_ws(st);return (at_end_q(st1)?st1:((()=>{let c=peek(st1);let line=get(st1,"line");let col=get(st1,"col");return ((c==="(")?emit(advance(st1),"LParen",c,line,col):((c===")")?emit(advance(st1),"RParen",c,line,col):((c==="[")?emit(advance(st1),"LBracket",c,line,col):((c==="]")?emit(advance(st1),"RBracket",c,line,col):((c==="{")?emit(advance(st1),"LBrace",c,line,col):((c==="}")?emit(advance(st1),"RBrace",c,line,col):((c==="\"")?read_string(st1):((c==="$")?read_variable(st1):((c===":")?read_keyword(st1):(is_digit_q(c)?read_number(st1):(((c==="-")&&is_digit_q(peek_at(st1,1)))?read_number_body(advance(st1),"-",false,line,col):(is_symbol_char_q(c)?read_symbol(st1):(true?emit(advance(st1),"Unknown",c,line,col):null)))))))))))));})()));})()); };
function lex_loop(st) { return ((()=>{let cur=st;return (()=>{(()=>{ while(not(at_end_q(skip_ws(cur)))) { (cur = read_token(cur)); } })();return get(cur,"tokens");})();})()); };
function lex(src) { return lex_loop(make_state(src)); };
