const _fl_str = (...xs) => xs.map(x => x==null?'null':String(x)).join('');const _fl_length = (x) => (x==null ? 0 : x.length);const _fl_substring = (s, a, b) => (b==null ? s.slice(a) : s.slice(a, b));const _fl_char_at = (s, i) => (s[i] || null);const _fl_replace = (s, a, b) => s.split(a).join(b);const _fl_starts_with = (s, p) => s.startsWith(p);const _fl_ends_with = (s, p) => s.endsWith(p);const _fl_contains = (s, p) => s.includes(p);const _fl_split = (s, sep) => s.split(sep);const _fl_join = (l, sep) => l.join(sep==null?'':sep);const _fl_trim = (s) => s.trim();const _fl_upper = (s) => s.toUpperCase();const _fl_lower = (s) => s.toLowerCase();const _fl_repeat = (s, n) => s.repeat(n);const _fl_index_of = (s, p) => s.indexOf(p);const _fl_first = (l) => (l==null || l.length===0 ? null : l[0]);const _fl_last = (l) => (l==null || l.length===0 ? null : l[l.length-1]);const _fl_rest = (l) => (l==null || l.length===0 ? [] : l.slice(1));const _fl_append = (a, b) => (Array.isArray(b) ? [...a, ...b] : [...a, b]);const _fl_slice = (l, a, b) => l.slice(a, b);const _fl_map = (f, l) => l.map(x => f(x));const _fl_filter = (f, l) => l.filter(x => f(x));const _fl_reduce = (f, init, l) => l.reduce((acc, x) => f(acc, x), init);const _fl_find = (f, l) => (l.find(x => f(x)) ?? null);const _fl_every = (f, l) => l.every(x => f(x));const _fl_some = (f, l) => l.some(x => f(x));const _fl_sort = (l, cmp) => [...l].sort(cmp || ((a,b)=>a<b?-1:a>b?1:0));const _fl_reverse = (l) => [...l].reverse();const _fl_flatten = (l) => l.flat(Infinity);const _fl_distinct = (l) => [...new Set(l)];const _fl_range = (a, b, s) => { let r=[]; let step=s||1; for(let i=a;i<b;i+=step)r.push(i); return r; };const _fl_take = (n, l) => l.slice(0, n);const _fl_drop = (n, l) => l.slice(n);const _fl_get = (o, k) => (o==null ? null : (o[k]===undefined ? null : o[k]));const _fl_keys = (o) => (o==null ? [] : Object.keys(o));const _fl_values = (o) => (o==null ? [] : Object.values(o));const _fl_entries = (o) => (o==null ? [] : Object.entries(o).map(([k,v])=>[k,v]));const _fl_has_key = (o, k) => (o!=null && k in o);const _fl_map_set = (o, k, v) => ({...o, [k]: v});const _fl_map_delete = (o, k) => { const c={...o}; delete c[k]; return c; };const _fl_merge = (...os) => Object.assign({}, ...os);const _fl_is_map = (x) => (x!=null && typeof x==='object' && !Array.isArray(x));const _fl_type_of = (x) => (x==null?'null':Array.isArray(x)?'list':typeof x);const _fl_file_read = (p) => require('fs').readFileSync(p, 'utf8');const _fl_file_write = (p, c) => require('fs').writeFileSync(p, c);const _fl_file_exists = (p) => require('fs').existsSync(p);const _fl_shell_capture = (cmd) => { try { const {execSync}=require('child_process'); return {stdout:execSync(cmd,{encoding:'utf8'}),stderr:'',code:0}; } catch(e) { return {stdout:'',stderr:String(e),code:1}; } };const _fl_empty_q = (x) => (x==null || x.length===0);
const is_digit_q = (c)=>((c==null)?false:((c>="0")&&(c<="9")));;
const is_alpha_q = (c)=>((c==null)?false:(((c>="a")&&(c<="z"))||((c>="A")&&(c<="Z"))));;
const is_alnum_q = (c)=>(is_digit_q(c)||is_alpha_q(c));;
const is_space_q = (c)=>((c===" ")||(c==="	")||(c==="
")||(c===""));;
const is_symbol_char_q = (c)=>((c==null)?false:(is_alnum_q(c)||(c==="-")||(c==="_")||(c==="?")||(c==="!")||(c==="/")||(c===".")||(c==="<")||(c===">")||(c==="=")||(c==="+")||(c==="*")||(c==="%")||(c==="&")||(c==="|")||(c==="^")||(c==="~")));;
const make_state = (src)=>null;;
const peek_at = (st,offset)=>((()=>{let src=_fl_get(st,"src");let i=(_fl_get(st,"idx")+offset);return ((i>=_fl_length(src))?null:_fl_char_at(src,i));})());;
const peek = (st)=>peek_at(st,0);;
const at_end_q = (st)=>(_fl_get(st,"idx")>=_fl_length(_fl_get(st,"src")));;
const advance = (st)=>((()=>{let c=peek(st);return ((c==="
")?null:null);})());;
const emit = (st,kind,value,sl,sc)=>null;;
const skip_comment = (st)=>(at_end_q(st)?st:((()=>{let c=peek(st);return ((c==="
")?advance(st):skip_comment(advance(st)));})()));;
const skip_ws = (st)=>(at_end_q(st)?st:((()=>{let c=peek(st);return (is_space_q(c)?skip_ws(advance(st)):((c===";")?skip_ws(skip_comment(st)):(true?st:null)));})()));;
const read_number_body = (st,acc,has_dot,line,col)=>(at_end_q(st)?emit(st,"Number",acc,line,col):((()=>{let c=peek(st);return (is_digit_q(c)?read_number_body(advance(st),_fl_str(acc,c),has_dot,line,col):(((c===".")&&(!has_dot))?read_number_body(advance(st),_fl_str(acc,c),true,line,col):(true?emit(st,"Number",acc,line,col):null)));})()));;
const read_number = (st)=>read_number_body(st,"",false,_fl_get(st,"line"),_fl_get(st,"col"));;
const translate_esc = (c)=>((c==="n")?"
":((c==="t")?"	":((c==="r")?"":((c==="\"")?"\"":((c==="\\")?"\\":(true?c:null))))));;
const read_string_body = (st,acc,line,col)=>(at_end_q(st)?emit(st,"String",acc,line,col):((()=>{let c=peek(st);return ((c==="\"")?emit(advance(st),"String",acc,line,col):((c==="\\")?((()=>{let st2=advance(st);let c2=peek(st2);return read_string_body(advance(st2),_fl_str(acc,translate_esc(c2)),line,col);})()):(true?read_string_body(advance(st),_fl_str(acc,c),line,col):null)));})()));;
const read_string = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_string_body(st1,"",line,col);})());;
const read_symbol_body_kind = (st,acc,line,col,kind)=>(at_end_q(st)?emit(st,kind,acc,line,col):((()=>{let c=peek(st);return (is_symbol_char_q(c)?read_symbol_body_kind(advance(st),_fl_str(acc,c),line,col,kind):emit(st,kind,acc,line,col));})()));;
const read_symbol = (st)=>read_symbol_body_kind(st,"",_fl_get(st,"line"),_fl_get(st,"col"),"Symbol");;
const read_variable = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Variable");})());;
const read_keyword = (st)=>((()=>{let line=_fl_get(st,"line");let col=_fl_get(st,"col");let st1=advance(st);return read_symbol_body_kind(st1,"",line,col,"Keyword");})());;
const read_token = (st)=>((()=>{let st1=skip_ws(st);return (at_end_q(st1)?st1:((()=>{let c=peek(st1);let line=_fl_get(st1,"line");let col=_fl_get(st1,"col");return ((c==="(")?emit(advance(st1),"LParen",c,line,col):((c===")")?emit(advance(st1),"RParen",c,line,col):((c==="[")?emit(advance(st1),"LBracket",c,line,col):((c==="]")?emit(advance(st1),"RBracket",c,line,col):((c==="{")?emit(advance(st1),"LBrace",c,line,col):((c==="}")?emit(advance(st1),"RBrace",c,line,col):((c==="\"")?read_string(st1):((c==="$")?read_variable(st1):((c===":")?read_keyword(st1):(is_digit_q(c)?read_number(st1):(((c==="-")&&is_digit_q(peek_at(st1,1)))?read_number_body(advance(st1),"-",false,line,col):(is_symbol_char_q(c)?read_symbol(st1):(true?emit(advance(st1),"Unknown",c,line,col):null)))))))))))));})()));})());;
const lex_loop = (st)=>((()=>{let st1=skip_ws(st);return (at_end_q(st1)?_fl_get(st1,"tokens"):lex_loop(read_token(st1)));})());;
const lex = (src)=>lex_loop(make_state(src));;
