"use strict";
const fs=require("fs"),path=require("path");
const IGN=new Set([".git","node_modules","dist","build",".cache"]);
function walk(root){const out=[];function go(dir){let es=[];try{es=fs.readdirSync(dir,{withFileTypes:true})}catch{return}for(const e of es){if(IGN.has(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())go(f);else if(e.isFile())out.push(f)}}go(root);return out}
function readJson(p){try{return JSON.parse(fs.readFileSync(p,"utf8"))}catch{return null}}
function balanced(s){let d=0,q=false,e=false;for(const c of s){if(q){if(e)e=false;else if(c==="\\")e=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==="(")d++;if(c===")")d--;if(d<0)return false}return !q&&d===0}
function effects(s){const a=[];if(/db[-_](query|get|find)|collection|afj[-_]db/i.test(s))a.push("db.read");if(/db[-_](exec|insert|update|delete)|append|snapshot/i.test(s))a.push("db.write");if(/fetch!?|http|network|server[-_]req/i.test(s))a.push("network");if(/file[-_](read|write)|read[-_]file|write[-_]file/i.test(s))a.push(/write/i.test(s)?"file.write":"file.read");if(/deploy|process|shell|exec/i.test(s))a.push("dangerous");return a.length?a:["pure"]}
function manifest(root){const files=walk(root),rel=f=>path.relative(root,f).replaceAll(path.sep,"/"),pkg=readJson(path.join(root,"package.json"))||{},existing=["freelang.project.json",".fl-project.json","fl.project.json"].map(x=>readJson(path.join(root,x))).find(Boolean),fl=files.filter(f=>f.endsWith(".fl")),front=files.filter(f=>f.endsWith(".flx")),routes=front.filter(f=>/(^|\/)pages\//.test(rel(f))).map(f=>{const x=rel(f).replace(/^pages\//,"").replace(/\.flx$/,"");return{path:"/"+(x==="index"?"":x),source:rel(f),methods:["GET"].concat(/render_post/.test(fs.readFileSync(f,"utf8"))?["POST"]:[])}}),collections=[];
for(const f of files.filter(f=>/\.(fl|flx|json|sql)$/.test(f)))for(const m of fs.readFileSync(f,"utf8").matchAll(/(?:collection|collection_name|table)\s*[=:]?\s*["']([A-Za-z_][\w-]*)["']/gi))if(!collections.some(c=>c.name===m[1]))collections.push({name:m[1],source:rel(f)});
const functions=[];for(const f of files.filter(f=>/\.(fl|flx)$/.test(f)))fs.readFileSync(f,"utf8").split(/\r?\n/).forEach((line,i)=>{const m=line.match(/\((?:defn|define)\s+([A-Za-z_][\w!?-]*)\s*(?:\[([^\]]*)\])?/);if(m)functions.push({name:m[1],signature:m[2]?"("+m[2].trim()+")":null,source:rel(f),line:i+1,effects:effects(line)})});
const tests=files.filter(f=>/(^|\/)(test|tests|spec)(\/|[-_.])|\.test\./.test(rel(f))).map(rel);
return{project:{name:existing?.project?.name||pkg.name||path.basename(root),root},runtime:existing?.runtime||{language:"FreeLang AFJ",cli:"fl",version:pkg.version||null},backend:existing?.backend||{files:fl.map(rel)},frontend:existing?.frontend||{language:front.length?"FreeLang Front":null,files:front.map(rel)},database:existing?.database||{engine:collections.length?"AFJ DB/declared project database":null,collections},routes:existing?.routes||routes,modules:existing?.modules||[...new Set(fl.map(rel).map(x=>x.split("/")[0]).filter(Boolean))],functions,collections:existing?.collections||collections,dependencies:existing?.dependencies||pkg.dependencies||{},tests:existing?.tests||{files:tests,commands:pkg.scripts||{}},deploy:existing?.deploy||{files:files.map(rel).filter(x=>/deploy|docker|systemd|ecosystem|compose/i.test(x))},health:{inspect:"available",warnings:[]},ai:{manifest:existing?"loaded":"generated-from-source",structured_errors:true,effects:true}}}
function inspect(root,args){const m=manifest(root),section=args.find(x=>!x.startsWith("--")),v=section&&m[section]!==undefined?m[section]:m;if(args.includes("--json"))console.log(JSON.stringify(v,null,2));else if(section)console.log(section+":\n"+JSON.stringify(v,null,2));else{console.log("project: "+m.project.name);for(const k of ["runtime","backend","frontend","database","routes","modules","functions","collections","dependencies","tests","deploy","health","ai"])console.log(k+": "+JSON.stringify(m[k]))}return 0}
function verify(root,args){const m=manifest(root),files=walk(root).filter(f=>/\.(fl|flx)$/.test(f)),errors=[];for(const f of files)if(!balanced(fs.readFileSync(f,"utf8")))errors.push({code:"FL_PARSE_001",phase:"syntax",file:path.relative(root,f),line:1,column:1,problem:"unbalanced_delimiters",symbol:null,message:"괄호 또는 문자열이 닫히지 않았습니다",suggestion:"괄호 쌍과 문자열 종료를 확인하세요"});const r={syntax:errors.length?"FAIL":"PASS",type:"SKIP",interpreter:"SKIP",native:"SKIP",db:m.database.collections.length?"PASS":"SKIP",api:m.routes.length?"PASS":"SKIP",front:m.frontend.files.length?"PASS":"SKIP",browser:"SKIP",regression:"SKIP",errors,can_claim_done:false};if(args.includes("--json"))console.log(JSON.stringify(r,null,2));else{for(const k of ["syntax","type","interpreter","native","db","api","front","browser","regression"])console.log(k.toUpperCase().padEnd(12)+r[k]);console.log("CAN_CLAIM_DONE="+r.can_claim_done);errors.forEach(x=>console.log(JSON.stringify(x)))}return errors.length?1:0}
module.exports={inspect,verify,manifest};