#!/usr/bin/env bash
# Rebuild self/all-c.fl from its source components.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUT="$ROOT_DIR/self/all-c.fl"

{
  printf '; self/all-c.fl -- AUTO-GENERATED C target compiler bundle\n'
  printf '; generated by scripts/build-all-c.sh\n\n'

  cat "$ROOT_DIR/self/parser.fl"

  printf '\n\n;; C target codegen\n'
  cat "$ROOT_DIR/self/codegen-c.fl"

  printf '\n\n;; IR validator\n'
  cat "$ROOT_DIR/self/ir-validator.fl"

  cat <<'FL'

;; C target driver
(defn path-dir [path]
  (let [[len (length path)]
        [last (loop [i (- len 1) r -1]
                (if (< i 0) r
                  (if (= (char-at path i) "/") i
                    (recur (- i 1) r))))]]
    (if (< last 0) "" (substring path 0 (+ last 1)))))

(defn append-all [acc items]
  (loop [i 0 a acc]
    (if (>= i (length items)) a
      (recur (+ i 1) (push a (get items i))))))

(defn expand-loads [nodes base-dir]
  (loop [i 0 acc []]
    (if (>= i (length nodes)) acc
      (let [[node (get nodes i)]]
        (if (and (= (get node :kind) "sexpr") (= (get node :op) "load"))
          (let [[path-node (get (get node :args) 0)]
                [rel-path (get path-node :value)]
                [try-path (if (str-starts-with rel-path "/") rel-path (str base-dir rel-path))]
                [src (file-read try-path)]
                [sub-dir (path-dir try-path)]
                [sub-raw (parse (lex src))]
                [expanded (expand-loads sub-raw sub-dir)]]
            (recur (+ i 1) (append-all acc expanded)))
          (recur (+ i 1) (push acc node)))))))

(defn compile-file-c [input output]
  (let [[src (file-read input)]
        [base-dir (path-dir input)]
        [raw (parse (lex src))]
        [nodes (expand-loads raw base-dir)]
        [_v (ir-validate nodes)]
        [c-code (generate-c nodes)]]
    (file-write output c-code)
    (println (str "Compiled C " input " -> " output))))

(defn cli-main []
  (let [[argv (cli-args)]]
    (if (or (null? argv) (= (length argv) 0))
      (println "usage: all-c.fl compile <input.fl> -o <output.c>")
      (let [[cmd (get argv 0)]]
        (if (= cmd "compile")
          (let [[input (get argv 1)]
                [output (if (and (>= (length argv) 4) (= (get argv 2) "-o"))
                          (get argv 3)
                          (str input ".c"))]]
            (compile-file-c input output))
          (let [[input (get argv 0)]
                [output (if (>= (length argv) 2) (get argv 1) (str input ".c"))]]
            (compile-file-c input output)))))))

(cli-main)
FL
} > "$OUT"

echo "generated $OUT"
